export const styles = {
  container: {
    width: '100%',
    alignSelf: 'stretch',
    boxSizing: 'border-box',
    minHeight: '100vh',
    padding: '24px 32px 40px 300px', // Added 300px padding left for the sidebar
    background: 'transparent',
    fontFamily: 'Inter, system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
    color: '#111015',
  },
  header: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '14px',
    padding: '14px 18px',
    borderRadius: '24px',
    background: '#ffffff',
    border: '1px solid #eef0f5',
    boxShadow: '0 8px 30px rgba(0, 0, 0, 0.04)',
  },
  logoSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    minWidth: 0,
  },
  logoBadge: {
    width: '40px',
    height: '40px',
    borderRadius: '12px',
    background: 'linear-gradient(135deg, #34d399, #10b981)',
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '20px',
    fontWeight: '800',
    boxShadow: '0 8px 16px rgba(16, 185, 129, 0.2)',
  },
  metaText: {
    color: '#64748b',
    fontSize: '14px',
    lineHeight: '1.85',
    display: 'inline-flex',
    flexWrap: 'wrap',
    gap: '0 10px',
  },
  navSection: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  navButton: {
    padding: '8px 16px',
    borderRadius: '999px',
    border: '1px solid transparent',
    background: 'transparent',
    color: '#64748b',
    fontWeight: '700',
    cursor: 'pointer',
    fontSize: '14px',
    transition: 'all 0.25s ease',
  },
  navButtonActive: {
    background: 'rgba(16, 185, 129, 0.08)',
    border: '1px solid rgba(16, 185, 129, 0.25)',
    color: '#10b981',
    boxShadow: 'none',
  },
  adminChip: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '7px 14px',
    borderRadius: '999px',
    background: '#ffffff',
    border: '1px solid #e2e8f0',
    color: '#111015',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.02)',
  },
  adminAvatar: {
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #34d399, #10b981)',
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '12px',
    fontWeight: '800',
  },
  logoutButtonStyle: {
    padding: '8px 16px',
    borderRadius: '999px',
    border: '1px solid #e2e8f0',
    background: '#ffffff',
    color: '#111015',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'all 0.25s ease',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.02)',
  },
  mainContent: {
    width: '100%',
    maxWidth: 'none',
    margin: '24px 0 0',
    display: 'flex',
    flexDirection: 'column',
    gap: '26px',
  },
  titleSection: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    textAlign: 'left',
    flexWrap: 'wrap',
    gap: '18px',
    width: '100%',
  },
  title: {
    margin: 0,
    fontSize: '36px',
    fontWeight: '800',
    color: '#111015',
    lineHeight: '1.03',
    maxWidth: '960px',
    width: '100%',
    letterSpacing: '-0.02em',
  },
  subTitleSection: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: '10px',
  },
  subTitle: {
    color: '#64748b',
    fontSize: '15px',
    fontWeight: '500',
  },
  countBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '50px',
    padding: '10px 16px',
    borderRadius: '999px',
    background: 'rgba(16, 185, 129, 0.08)',
    color: '#10b981',
    fontWeight: '700',
    fontSize: '13px',
    boxShadow: 'inset 0 0 0 1px rgba(16, 185, 129, 0.18)',
  },
  controlsSection: {
    display: 'grid',
    gridTemplateColumns: '1fr',
    gap: '16px',
  },
  actionButtons: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  searchInput: {
    width: '100%',
    maxWidth: '300px',
    padding: '10px 16px',
    borderRadius: '999px',
    border: '1px solid #e2e8f0',
    background: '#ffffff',
    color: '#111015',
    fontSize: '14px',
    outline: 'none',
    boxSizing: 'border-box',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.02)',
    transition: 'border-color 0.25s ease, box-shadow 0.25s ease',
  },
  selectDropdown: {
    padding: '10px 16px',
    borderRadius: '999px',
    border: '1px solid #e2e8f0',
    background: '#ffffff',
    color: '#111015',
    fontSize: '14px',
    outline: 'none',
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.02)',
    transition: 'border-color 0.25s ease, box-shadow 0.25s ease',
  },
  statusSelectBorder: (status) => ({
    borderColor:
      status === 'Online' ? 'rgba(16, 185, 129, 0.4)' :
      status === 'Offline' ? '#e2e8f0' :
      status === 'Warning' ? 'rgba(245, 158, 11, 0.4)' :
      '#e2e8f0',
  }),
  enabledSelectBorder: (status) => ({
    borderColor:
      status === 'Enabled' ? 'rgba(16, 185, 129, 0.4)' :
      '#e2e8f0',
  }),
  iconButton: {
    width: '40px',
    height: '40px',
    borderRadius: '8px',
    border: '1px solid #edf0f5',
    background: '#ffffff',
    color: '#64748b',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.02)',
    transition: 'transform 0.2s ease, background-color 0.25s ease',
  },
  actionButton: {
    padding: '9px 18px',
    borderRadius: '999px',
    border: '1px solid #edf0f5',
    background: '#ffffff',
    color: '#64748b',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.02)',
    transition: 'all 0.25s ease',
  },
  primaryActionButton: {
    marginLeft: 'auto',
    padding: '10px 24px',
    borderRadius: '999px',
    border: 'none',
    background: 'linear-gradient(135deg, #34d399, #10b981)',
    color: '#ffffff',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
    boxShadow: '0 8px 16px rgba(16, 185, 129, 0.2)',
    transition: 'all 0.25s ease',
  },
  deleteSelectedBtn: {
    padding: '9px 18px',
    borderRadius: '999px',
    border: '1px solid rgba(239, 68, 68, 0.18)',
    background: 'rgba(239, 68, 68, 0.08)',
    color: '#ef4444',
    fontWeight: '700',
    cursor: 'pointer',
    boxShadow: '0 4px 12px rgba(239, 68, 68, 0.05)',
  },
  cancelButton: {
    padding: '9px 18px',
    borderRadius: '999px',
    border: '1px solid #edf0f5',
    background: '#ffffff',
    color: '#64748b',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'all 0.25s ease',
  },
  paginationBar: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '28px 28px 24px',
    minHeight: '132px',
    borderBottom: '1px solid #eef0f5',
    minWidth: 0,
  },
  selectALLButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '48px',
    height: '48px',
    borderRadius: '12px',
    background: '#ffffff',
    border: '1px solid #edf0f5',
    color: '#64748b',
  },
  checkbox: {
    width: '18px',
    height: '18px',
    borderRadius: '8px',
    border: '1px solid #cbd5e1',
    accentColor: '#10b981',
  },
  paginationInfo: {
    color: '#64748b',
    fontSize: '14px',
    flex: '1 1 220px',
    minWidth: '180px',
  },
  paginationControls: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flex: '1 1 320px',
    minWidth: '220px',
  },
  pageSizeSelect: {
    width: '78px',
    padding: '10px 12px',
    borderRadius: '8px',
    border: '1px solid #edf0f5',
    background: '#ffffff',
    color: '#111015',
    fontSize: '14px',
    outline: 'none',
    cursor: 'pointer',
  },
  pageNavButton: {
    padding: '10px 18px',
    borderRadius: '8px',
    border: '1px solid #edf0f5',
    background: '#ffffff',
    color: '#64748b',
    cursor: 'pointer',
    fontWeight: '700',
    transition: 'all 0.25s ease',
    minWidth: '106px',
    whiteSpace: 'nowrap',
  },
  pageNumber: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '38px',
    minWidth: '38px',
    height: '38px',
    padding: 0,
    borderRadius: '999px',
    border: '1px solid #edf0f5',
    background: '#ffffff',
    color: '#64748b',
    cursor: 'pointer',
  },
  pageNumberActive: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '38px',
    minWidth: '38px',
    height: '38px',
    padding: 0,
    borderRadius: '999px',
    border: '1px solid #10b981',
    background: '#10b981',
    color: '#ffffff',
    fontWeight: '700',
  },
  paginationEllipsis: {
    minWidth: '28px',
    color: '#111015',
    textAlign: 'center',
    fontWeight: '700',
  },
  assetPanel: {
    minHeight: '430px',
    borderRadius: '24px',
    background: '#ffffff',
    border: '1px solid #eef0f5',
    boxShadow: '0 8px 30px rgba(0, 0, 0, 0.04)',
    overflow: 'hidden',
  },
  deviceList: {
    display: 'grid',
    gap: 0,
    minHeight: '268px',
  },
  deviceCard: {
    borderRadius: 0,
    background: 'transparent',
    boxShadow: 'none',
    border: 0,
    borderBottom: '1px solid #eef0f5',
    overflow: 'hidden',
  },
  deviceHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '16px',
    minHeight: '92px',
    padding: '14px 28px',
  },
  deviceHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    flexWrap: 'wrap',
  },
  deviceNumber: {
    fontFamily: 'Inter, system-ui, sans-serif',
    fontWeight: '700',
    color: '#10b981',
    fontSize: '13px',
    minWidth: '28px',
  },
  deviceName: {
    fontWeight: '700',
    color: '#111015', // Changed to dark text color for clear visibility
    fontSize: '16px',
  },
  assetIdBadge: {
    width: '18px',
    height: '8px',
    padding: 0,
    borderRadius: '999px',
    background: 'rgba(16, 185, 129, 0.08)',
    color: '#10b981',
    fontSize: 0,
    overflow: 'hidden',
  },
  badge: (status) => ({
    padding: '8px 14px',
    borderRadius: '999px',
    border: '1px solid #edf0f5',
    background:
      status === 'Online' ? 'rgba(16, 185, 129, 0.08)' :
      status === 'Offline' ? 'rgba(100, 116, 139, 0.08)' :
      status === 'Warning' ? 'rgba(245, 158, 11, 0.08)' :
      'rgba(100, 116, 139, 0.08)',
    color:
      status === 'Online' ? '#10b981' :
      status === 'Offline' ? '#64748b' :
      status === 'Warning' ? '#d97706' :
      '#64748b',
    fontWeight: '700',
    fontSize: '12px',
  }),
  deviceHeaderRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap',
  },
  expandIcon: {
    cursor: 'pointer',
    width: '40px',
    height: '40px',
    padding: 0,
    borderRadius: '8px',
    color: '#64748b',
    transition: 'transform 0.2s ease',
    background: '#f8fafc',
    border: '1px solid #edf0f5',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyState: {
    minHeight: '268px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#64748b',
    fontSize: '14px',
  },
  deviceDetails: {
    padding: '24px 24px 28px',
    background: '#f8fafc',
    borderTop: '1px solid #edf0f5',
  },
  detailsHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '16px',
    marginBottom: '18px',
  },
  detailsTitle: {
    fontWeight: '700',
    color: '#111015',
    fontSize: '16px',
  },
  detailsActions: {
    display: 'flex',
    gap: '10px',
    flexWrap: 'wrap',
  },
  saveButton: {
    padding: '12px 22px',
    borderRadius: '999px',
    border: 'none',
    background: 'linear-gradient(135deg, #34d399, #10b981)',
    color: '#ffffff',
    fontWeight: '700',
    cursor: 'pointer',
    boxShadow: '0 8px 16px rgba(16, 185, 129, 0.2)',
  },
  editButton: {
    padding: '12px 22px',
    borderRadius: '999px',
    border: '1px solid #edf0f5',
    background: '#ffffff',
    color: '#64748b',
    fontWeight: '700',
    cursor: 'pointer',
  },
  detailItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    minWidth: 0,
  },
  detailLabel: {
    fontSize: '13px',
    fontWeight: '700',
    color: '#64748b',
  },
  editInput: {
    width: '100%',
    padding: '14px 16px',
    borderRadius: '14px',
    border: '1px solid #edf0f5',
    background: '#ffffff',
    color: '#111015',
    outline: 'none',
  },
  detailValue: {
    color: '#111015',
    fontSize: '14px',
  },
  mono: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  },
  section: {
    marginTop: '22px',
    borderRadius: '16px',
    background: '#ffffff',
    border: '1px solid #eef0f5',
    boxShadow: 'none',
    padding: '22px',
  },
  sectionTitle: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    fontWeight: '700',
    color: '#111015',
    fontSize: '15px',
    marginBottom: '16px',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  sectionGrid: {
    display: 'grid',
    gap: '18px',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
  },
  statusRow: {
    display: 'grid',
    gap: '16px',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    marginTop: '18px',
  },
  statusField: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  timestampBar: {
    marginTop: '22px',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
    alignItems: 'center',
  },
  timestampChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px 16px',
    borderRadius: '999px',
    background: '#f1f5f9',
    color: '#64748b',
    fontSize: '13px',
    border: '1px solid #e2e8f0',
  },
  timestampSep: {
    width: '1px',
    height: '20px',
    background: '#e2e8f0',
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '18px',
    zIndex: 2000,
  },
  modal: {
    width: 'min(100%, 760px)',
    maxHeight: '88vh',
    overflowY: 'auto',
    background: '#ffffff',
    borderRadius: '24px',
    padding: '28px 30px',
    border: '1px solid #eef0f5',
    boxShadow: '0 20px 48px rgba(0, 0, 0, 0.1)',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
  },
  modalTitle: {
    margin: 0,
    fontSize: '20px',
    fontWeight: '700',
    color: '#111015',
  },
  modalBody: {
    width: '100%',
  },
  modalClose: {
    background: 'transparent',
    border: 'none',
    color: '#10b981',
    cursor: 'pointer',
    fontSize: '18px',
    width: '34px',
    height: '34px',
    borderRadius: '8px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '14px 16px',
  },
  modalField: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  modalLabel: {
    fontSize: '12px',
    fontWeight: '700',
    color: '#64748b',
  },
  modalInput: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '8px',
    border: '1px solid #edf0f5',
    background: '#f8fafc',
    color: '#111015',
    fontSize: '14px',
    outline: 'none',
    boxSizing: 'border-box',
  },
  modalSelect: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '8px',
    border: '1px solid #edf0f5',
    background: '#f8fafc',
    color: '#111015',
    fontSize: '14px',
    outline: 'none',
    cursor: 'pointer',
    boxSizing: 'border-box',
  },
  modalFooter: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: '10px',
  },
  modalCancel: {
    padding: '10px 20px',
    borderRadius: '999px',
    border: '1px solid #edf0f5',
    background: '#ffffff',
    color: '#64748b',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
  },
  modalCreate: {
    padding: '10px 20px',
    borderRadius: '999px',
    border: 'none',
    background: 'linear-gradient(135deg, #34d399, #10b981)',
    color: '#ffffff',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
    boxShadow: '0 8px 16px rgba(16, 185, 129, 0.2)',
  },
};
