export const styles = {
  container: {
    width: '100%',
    alignSelf: 'stretch',
    boxSizing: 'border-box',
    minHeight: '100vh',
    padding: '24px 32px 40px',
    background: '#f7f7f5',
    fontFamily: 'Inter, system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
    color: '#181816',
  },
  header: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '14px',
    padding: '14px 18px',
    borderRadius: '8px',
    background: 'rgba(255, 255, 255, 0.92)',
    border: '1px solid rgba(24, 24, 22, 0.06)',
    boxShadow: '0 14px 32px rgba(24, 24, 22, 0.10)',
    backdropFilter: 'blur(20px)',
  },
  logoSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    minWidth: 0,
  },
  logoBadge: {
    width: '40px',
    height: '40px',
    borderRadius: '8px',
    background: 'linear-gradient(135deg, #ff7043, #f4511e)',
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '20px',
    fontWeight: '800',
    boxShadow: '0 16px 32px rgba(244, 81, 30, 0.18)',
  },
  metaText: {
    color: '#70737b',
    fontSize: '14px',
    lineHeight: '1.85',
    display: 'inline-flex',
    flexWrap: 'wrap',
    gap: '0 10px',
  },
  navSection: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  navButton: {
    padding: '8px 16px',
    borderRadius: '999px',
    border: '1px solid #e3e3df',
    background: 'rgba(255, 255, 255, 0.9)',
    color: '#181816',
    fontWeight: '700',
    cursor: 'pointer',
    fontSize: '14px',
    transition: 'all 0.25s ease',
    boxShadow: '0 12px 26px rgba(24, 24, 22, 0.05)',
  },
  navButtonActive: {
    background: '#181816',
    border: '1px solid #181816',
    color: '#ffffff',
    boxShadow: '0 16px 26px rgba(24, 24, 22, 0.14)',
  },
  adminChip: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '7px 14px',
    borderRadius: '999px',
    background: '#181816',
    border: '1px solid #181816',
    color: '#ffffff',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
    boxShadow: '0 16px 32px rgba(24, 24, 22, 0.12)',
  },
  adminAvatar: {
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #ff7043, #f4511e)',
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '12px',
    fontWeight: '800',
  },
  logoutButtonStyle: {
    padding: '8px 16px',
    borderRadius: '999px',
    border: '1px solid #e3e3df',
    background: 'rgba(255, 255, 255, 0.95)',
    color: '#181816',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'all 0.25s ease',
    boxShadow: '0 12px 24px rgba(24, 24, 22, 0.06)',
  },
  mainContent: {
    width: '100%',
    maxWidth: 'none',
    margin: '24px 0 0',
    display: 'flex',
    flexDirection: 'column',
    gap: '26px',
  },
  titleSection: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    textAlign: 'left',
    flexWrap: 'wrap',
    gap: '18px',
    width: '100%',
  },
  title: {
    margin: 0,
    fontSize: '36px',
    fontWeight: '700',
    color: '#181816',
    lineHeight: '1.03',
    maxWidth: '960px',
    width: '100%',
  },
  subTitleSection: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: '10px',
  },
  subTitle: {
    color: '#70737b',
    fontSize: '15px',
    fontWeight: '500',
  },
  countBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '50px',
    padding: '10px 16px',
    borderRadius: '999px',
    background: 'rgba(255, 112, 67, 0.12)',
    color: '#f4511e',
    fontWeight: '700',
    fontSize: '13px',
    boxShadow: 'inset 0 0 0 1px rgba(255, 112, 67, 0.18)',
  },
  controlsSection: {
    display: 'grid',
    gridTemplateColumns: '1fr',
    gap: '16px',
  },
  actionButtons: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  searchInput: {
    width: '100%',
    maxWidth: '300px',
    padding: '10px 14px',
    borderRadius: '8px',
    border: '1px solid #e3e3df',
    background: 'rgba(255, 255, 255, 0.96)',
    color: '#181816',
    fontSize: '14px',
    outline: 'none',
    boxSizing: 'border-box',
    boxShadow: 'inset 0 1px 4px rgba(24, 24, 22, 0.04)',
    transition: 'border-color 0.25s ease, box-shadow 0.25s ease',
  },
  selectDropdown: {
    padding: '10px 14px',
    borderRadius: '8px',
    border: '1px solid #e3e3df',
    background: 'rgba(255, 255, 255, 0.96)',
    color: '#181816',
    fontSize: '14px',
    outline: 'none',
    cursor: 'pointer',
    boxShadow: 'inset 0 1px 4px rgba(24, 24, 22, 0.04)',
    transition: 'border-color 0.25s ease, box-shadow 0.25s ease',
  },
  statusSelectBorder: (status) => ({
    borderColor:
      status === 'Online' ? 'rgba(255, 112, 67, 0.42)' :
      status === 'Offline' ? 'rgba(24, 24, 22, 0.24)' :
      status === 'Warning' ? 'rgba(255, 112, 67, 0.55)' :
      '#e3e3df',
  }),
  enabledSelectBorder: (status) => ({
    borderColor:
      status === 'Enabled' ? 'rgba(255, 112, 67, 0.42)' :
      'rgba(24, 24, 22, 0.18)',
  }),
  iconButton: {
    width: '40px',
    height: '40px',
    borderRadius: '8px',
    border: '1px solid #e3e3df',
    background: 'rgba(255, 255, 255, 0.96)',
    color: '#181816',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    boxShadow: '0 14px 28px rgba(24, 24, 22, 0.06)',
    transition: 'transform 0.2s ease, background-color 0.25s ease',
  },
  actionButton: {
    padding: '9px 18px',
    borderRadius: '999px',
    border: '1px solid #e3e3df',
    background: 'rgba(255, 255, 255, 0.95)',
    color: '#181816',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
    boxShadow: '0 14px 30px rgba(24, 24, 22, 0.06)',
    transition: 'all 0.25s ease',
  },
  primaryActionButton: {
    marginLeft: 'auto',
    padding: '10px 24px',
    borderRadius: '8px',
    border: '1px solid #181816',
    background: '#181816',
    color: '#ffffff',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
    boxShadow: '0 12px 24px rgba(24, 24, 22, 0.16)',
    transition: 'all 0.25s ease',
  },
  deleteSelectedBtn: {
    padding: '9px 18px',
    borderRadius: '999px',
    border: '1px solid rgba(244, 81, 30, 0.26)',
    background: 'rgba(255, 112, 67, 0.11)',
    color: '#f4511e',
    fontWeight: '700',
    cursor: 'pointer',
    boxShadow: '0 14px 30px rgba(217, 140, 80, 0.12)',
  },
  cancelButton: {
    padding: '9px 18px',
    borderRadius: '999px',
    border: '1px solid #e3e3df',
    background: 'rgba(255, 255, 255, 0.92)',
    color: '#181816',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'all 0.25s ease',
  },
  paginationBar: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '28px 28px 24px',
    minHeight: '132px',
    borderBottom: '1px solid #e8e8e4',
    minWidth: 0,
  },
  selectALLButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '48px',
    height: '48px',
    borderRadius: '6px',
    background: 'rgba(255, 255, 255, 0.96)',
    border: '1px solid #e3e3df',
  },
  checkbox: {
    width: '18px',
    height: '18px',
    borderRadius: '8px',
    border: '1px solid rgba(207, 176, 116, 0.8)',
    accentColor: '#ff7043',
  },
  paginationInfo: {
    color: '#70737b',
    fontSize: '14px',
    flex: '1 1 220px',
    minWidth: '180px',
  },
  paginationControls: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flex: '1 1 320px',
    minWidth: '220px',
  },
  pageSizeSelect: {
    width: '78px',
    padding: '10px 12px',
    borderRadius: '8px',
    border: '1px solid #e3e3df',
    background: '#ffffff',
    color: '#181816',
    fontSize: '14px',
    outline: 'none',
    cursor: 'pointer',
  },
  pageNavButton: {
    padding: '10px 18px',
    borderRadius: '8px',
    border: '1px solid #e3e3df',
    background: 'rgba(255, 255, 255, 0.95)',
    color: '#181816',
    cursor: 'pointer',
    fontWeight: '700',
    transition: 'all 0.25s ease',
    minWidth: '106px',
    whiteSpace: 'nowrap',
  },
  pageNumber: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '38px',
    minWidth: '38px',
    height: '38px',
    padding: 0,
    borderRadius: '999px',
    border: '1px solid #e3e3df',
    background: 'rgba(255, 255, 255, 0.95)',
    color: '#70737b',
    cursor: 'pointer',
  },
  pageNumberActive: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '38px',
    minWidth: '38px',
    height: '38px',
    padding: 0,
    borderRadius: '999px',
    border: '1px solid rgba(255, 112, 67, 0.55)',
    background: '#ff7043',
    color: '#ffffff',
    fontWeight: '700',
  },
  paginationEllipsis: {
    minWidth: '28px',
    color: '#181816',
    textAlign: 'center',
    fontWeight: '700',
  },
  assetPanel: {
    minHeight: '430px',
    borderRadius: '8px',
    background: 'rgba(255, 255, 255, 0.96)',
    border: '1px solid #e5e5e1',
    boxShadow: '0 16px 38px rgba(24, 24, 22, 0.08)',
    overflow: 'hidden',
  },
  deviceList: {
    display: 'grid',
    gap: 0,
    minHeight: '268px',
  },
  deviceCard: {
    borderRadius: 0,
    background: 'transparent',
    boxShadow: 'none',
    border: 0,
    borderBottom: '1px solid #ecece8',
    overflow: 'hidden',
  },
  deviceHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '16px',
    minHeight: '92px',
    padding: '14px 28px',
  },
  deviceHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    flexWrap: 'wrap',
  },
  deviceNumber: {
    fontFamily: 'Inter, system-ui, sans-serif',
    fontWeight: '700',
    color: '#f4511e',
    fontSize: '13px',
    minWidth: '28px',
  },
  deviceName: {
    fontWeight: '700',
    color: '#181816',
    fontSize: '16px',
  },
  assetIdBadge: {
    width: '18px',
    height: '8px',
    padding: 0,
    borderRadius: '999px',
    background: 'rgba(255, 112, 67, 0.10)',
    color: '#f4511e',
    fontSize: 0,
    overflow: 'hidden',
  },
  badge: (status) => ({
    padding: '8px 14px',
    borderRadius: '999px',
    border: '1px solid rgba(24, 24, 22, 0.05)',
    background:
      status === 'Online' ? 'rgba(255, 112, 67, 0.11)' :
      status === 'Offline' ? 'rgba(24, 24, 22, 0.08)' :
      status === 'Warning' ? 'rgba(255, 112, 67, 0.10)' :
      'rgba(241, 245, 249, 0.95)',
    color:
      status === 'Online' ? '#f4511e' :
      status === 'Offline' ? '#181816' :
      status === 'Warning' ? '#f4511e' :
      '#70737b',
    fontWeight: '700',
    fontSize: '12px',
  }),
  deviceHeaderRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap',
  },
  expandIcon: {
    cursor: 'pointer',
    width: '40px',
    height: '40px',
    padding: 0,
    borderRadius: '8px',
    color: '#181816',
    transition: 'transform 0.2s ease',
    background: 'rgba(255, 255, 255, 0.95)',
    border: '1px solid #e3e3df',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyState: {
    minHeight: '268px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#70737b',
    fontSize: '14px',
  },
  deviceDetails: {
    padding: '24px 24px 28px',
    background: 'rgba(255, 255, 255, 0.92)',
    borderTop: '1px solid #ededeb',
  },
  detailsHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '16px',
    marginBottom: '18px',
  },
  detailsTitle: {
    fontWeight: '700',
    color: '#181816',
    fontSize: '16px',
  },
  detailsActions: {
    display: 'flex',
    gap: '10px',
    flexWrap: 'wrap',
  },
  saveButton: {
    padding: '12px 22px',
    borderRadius: '999px',
    border: 'none',
    background: 'linear-gradient(135deg, #ff7043, #f4511e)',
    color: '#ffffff',
    fontWeight: '700',
    cursor: 'pointer',
    boxShadow: '0 18px 30px rgba(244, 81, 30, 0.22)',
  },
  editButton: {
    padding: '12px 22px',
    borderRadius: '999px',
    border: '1px solid #e3e3df',
    background: 'rgba(255, 255, 255, 0.96)',
    color: '#181816',
    fontWeight: '700',
    cursor: 'pointer',
  },
  detailItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    minWidth: 0,
  },
  detailLabel: {
    fontSize: '13px',
    fontWeight: '700',
    color: '#70737b',
  },
  editInput: {
    width: '100%',
    padding: '14px 16px',
    borderRadius: '14px',
    border: '1px solid #e3e3df',
    background: 'rgba(255, 255, 255, 0.95)',
    color: '#181816',
    outline: 'none',
    boxShadow: 'inset 0 2px 10px rgba(33, 30, 27, 0.05)',
  },
  detailValue: {
    color: '#2d2d2a',
    fontSize: '14px',
  },
  mono: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  },
  section: {
    marginTop: '22px',
    borderRadius: '8px',
    background: 'rgba(255, 255, 255, 0.95)',
    border: '1px solid rgba(24, 24, 22, 0.06)',
    boxShadow: '0 16px 34px rgba(24, 24, 22, 0.05)',
    padding: '22px',
  },
  sectionTitle: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    fontWeight: '700',
    color: '#181816',
    fontSize: '15px',
    marginBottom: '16px',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  sectionGrid: {
    display: 'grid',
    gap: '18px',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
  },
  statusRow: {
    display: 'grid',
    gap: '16px',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    marginTop: '18px',
  },
  statusField: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  timestampBar: {
    marginTop: '22px',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
    alignItems: 'center',
  },
  timestampChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px 16px',
    borderRadius: '999px',
    background: 'rgba(255, 112, 67, 0.10)',
    color: '#2d2d2a',
    fontSize: '13px',
    border: '1px solid rgba(255, 112, 67, 0.16)',
  },
  timestampSep: {
    width: '1px',
    height: '20px',
    background: '#e3e3df',
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(34, 28, 20, 0.25)',
    backdropFilter: 'blur(10px)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '18px',
    zIndex: 2000,
  },
  modal: {
    width: 'min(100%, 760px)',
    maxHeight: '88vh',
    overflowY: 'auto',
    background: '#ffffff',
    borderRadius: '12px',
    padding: '22px 24px',
    border: '1px solid rgba(24, 24, 22, 0.08)',
    boxShadow: '0 34px 80px rgba(24, 24, 22, 0.16)',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
  },
  modalTitle: {
    margin: 0,
    fontSize: '20px',
    fontWeight: '700',
    color: '#181816',
  },
  modalBody: {
    width: '100%',
  },
  modalClose: {
    background: 'transparent',
    border: 'none',
    color: '#f4511e',
    cursor: 'pointer',
    fontSize: '18px',
    width: '34px',
    height: '34px',
    borderRadius: '8px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '14px 16px',
  },
  modalField: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  modalLabel: {
    fontSize: '12px',
    fontWeight: '700',
    color: '#70737b',
  },
  modalInput: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '8px',
    border: '1px solid #e3e3df',
    background: 'rgba(255, 255, 255, 0.95)',
    color: '#181816',
    fontSize: '14px',
    outline: 'none',
    boxSizing: 'border-box',
    boxShadow: 'inset 0 2px 12px rgba(33, 30, 27, 0.05)',
  },
  modalSelect: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '8px',
    border: '1px solid #e3e3df',
    background: 'rgba(255, 255, 255, 0.95)',
    color: '#181816',
    fontSize: '14px',
    outline: 'none',
    cursor: 'pointer',
    boxSizing: 'border-box',
    boxShadow: 'inset 0 2px 12px rgba(33, 30, 27, 0.05)',
  },
  modalFooter: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: '10px',
  },
  modalCancel: {
    padding: '10px 20px',
    borderRadius: '999px',
    border: '1px solid #e3e3df',
    background: 'rgba(255, 255, 255, 0.94)',
    color: '#181816',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
  },
  modalCreate: {
    padding: '10px 20px',
    borderRadius: '999px',
    border: 'none',
    background: 'linear-gradient(135deg, #ff7043, #f4511e)',
    color: '#ffffff',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
  },
};
