export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    minHeight: '100vh',
    padding: '32px',
    margin: '0 auto',
    maxWidth: '1200px',
    width: '100%',
    boxSizing: 'border-box',
    background: 'transparent',
    fontFamily: 'Inter, system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
    color: '#ffffff',
    gap: '32px',
  },
  header: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '32px',
    alignItems: 'center',
    padding: '32px',
    borderRadius: '32px',
    background: '#121215',
    border: '1px solid #1f1f24',
    boxShadow: '0 8px 30px rgba(0, 0, 0, 0.4)',
  },
  profileSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '18px',
    minWidth: 0,
  },
  avatarCircle: {
    width: '62px',
    height: '62px',
    borderRadius: '18px',
    background: 'linear-gradient(135deg, #10b981, #059669)',
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '28px',
    fontWeight: '800',
    boxShadow: '0 10px 25px rgba(16, 185, 129, 0.25)',
  },
  username: {
    fontSize: '22px',
    fontWeight: '700',
    color: '#ffffff',
  },
  empId: {
    fontSize: '14px',
    color: '#a1a1aa',
    marginTop: '4px',
  },
  notificationBar: {
    flex: '1 1 280px',
    minWidth: '260px',
    padding: '20px 24px',
    borderRadius: '20px',
    background: 'rgba(16, 185, 129, 0.06)',
    color: '#10b981',
    fontSize: '15px',
    fontWeight: '600',
    boxShadow: '0 4px 12px rgba(16, 185, 129, 0.05)',
    border: '1px solid rgba(16, 185, 129, 0.15)',
  },
  joiningInfo: {
    minWidth: '180px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    color: '#a1a1aa',
    textAlign: 'right',
    fontSize: '14px',
    lineHeight: '1.7',
  },
  backBtn: {
    margin: '0 auto',
    padding: '8px 20px',
    borderRadius: '20px',
    background: '#18181c',
    border: '1px solid #27272a',
    color: '#10b981',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '700',
    alignSelf: 'center',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.2)',
    transition: 'all 0.2s ease',
  },
  mainGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '32px',
    marginTop: '32px',
    width: '100%',
  },
  devicesPanel: {
    padding: '32px',
    borderRadius: '32px',
    background: '#121215',
    border: '1px solid #1f1f24',
    boxShadow: '0 8px 30px rgba(0, 0, 0, 0.4)',
  },
  devicesPanelTitle: {
    margin: 0,
    fontSize: '15px',
    fontWeight: '700',
    color: '#ffffff',
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
  },
  noDevices: {
    color: '#a1a1aa',
    fontSize: '14px',
    marginTop: '16px',
  },
  deviceRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '12px',
    padding: '14px 0',
    borderBottom: '1px solid #1f1f24',
    fontSize: '14px',
  },
  deviceRowId: {
    color: '#10b981',
    fontWeight: '700',
    minWidth: '24px',
  },
  deviceRowName: {
    fontWeight: '700',
    color: '#ffffff',
    flex: 1,
    minWidth: '120px',
  },
  deviceRowAsset: {
    color: '#10b981',
    fontSize: '12px',
    background: 'rgba(16, 185, 129, 0.08)',
    borderRadius: '999px',
    padding: '5px 12px',
  },
  deviceRowStatus: {
    fontSize: '12px',
    fontWeight: '700',
  },
  messagePanel: {
    padding: '32px',
    borderRadius: '32px',
    background: '#121215',
    border: '1px solid #1f1f24',
    boxShadow: '0 8px 30px rgba(0, 0, 0, 0.4)',
    display: 'flex',
    flexDirection: 'column',
    gap: '18px',
  },
  searchInput: {
    width: '100%',
    padding: '14px 18px',
    borderRadius: '16px',
    border: '1px solid #27272a',
    background: '#18181c',
    outline: 'none',
    fontSize: '14px',
    color: '#ffffff',
  },
  chatBox: {
    minHeight: '260px',
    borderRadius: '18px',
    background: '#18181c',
    border: '1px solid #1f1f24',
  },
  messageInput: {
    width: '100%',
    padding: '14px 18px',
    borderRadius: '16px',
    border: '1px solid #27272a',
    background: '#18181c',
    outline: 'none',
    fontSize: '14px',
    color: '#ffffff',
  },
  logoutBtn: {
    background: 'linear-gradient(135deg, #ef4444, #dc2626)',
    color: '#ffffff',
    border: 'none',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '700',
    padding: '10px 18px',
    borderRadius: '14px',
    boxShadow: '0 8px 16px rgba(239, 68, 68, 0.3)',
    transition: 'transform 0.2s ease, opacity 0.2s ease',
  },
  profileImg: {
    width: '100%',
    height: '100%',
    borderRadius: '18px',
    objectFit: 'cover',
  },
  uploadBtn: {
    background: 'rgba(16, 185, 129, 0.08)',
    color: '#10b981',
    border: 'none',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: '700',
    padding: '8px 14px',
    borderRadius: '12px',
    marginTop: '8px',
    transition: 'background 0.2s ease',
  },
  editIconBtn: {
    background: 'none',
    border: 'none',
    color: '#10b981',
    cursor: 'pointer',
    fontSize: '14px',
    padding: '4px 8px',
    marginLeft: '6px',
  },
  usernameInput: {
    padding: '6px 12px',
    borderRadius: '10px',
    border: '1px solid #10b981',
    background: '#18181c',
    outline: 'none',
    fontSize: '18px',
    fontWeight: '700',
    color: '#ffffff',
    width: '180px',
  },
  editActionBtn: (isSave) => ({
    background: isSave ? '#10b981' : '#ef4444',
    color: '#ffffff',
    border: 'none',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: '700',
    padding: '6px 10px',
    borderRadius: '8px',
    marginLeft: '6px',
  }),
  searchRow: {
    display: 'flex',
    gap: '10px',
  },
  searchBtn: {
    background: 'linear-gradient(135deg, #10b981, #059669)',
    color: '#ffffff',
    border: 'none',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '700',
    padding: '12px 18px',
    borderRadius: '16px',
    boxShadow: '0 8px 20px rgba(16, 185, 129, 0.25)',
  },
  searchResultsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    overflowY: 'auto',
    maxHeight: '280px',
    paddingRight: '4px',
  },
  searchResultItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    borderRadius: '14px',
    backgroundColor: '#18181c',
    border: '1px solid #1f1f24',
  },
  resultUserMeta: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  resultUsername: {
    fontWeight: '700',
    fontSize: '14px',
    color: '#ffffff',
  },
  resultSub: {
    fontSize: '12px',
    color: '#a1a1aa',
  },
  badgeEnabled: {
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
    color: '#10b981',
    fontSize: '11px',
    fontWeight: '700',
    padding: '4px 10px',
    borderRadius: '999px',
    display: 'inline-block',
  },
  badgeDisabled: {
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    color: '#ef4444',
    fontSize: '11px',
    fontWeight: '700',
    padding: '4px 10px',
    borderRadius: '999px',
    display: 'inline-block',
  },
  toggleBtn: (isEnabled) => ({
    background: isEnabled ? 'rgba(239, 68, 68, 0.08)' : 'rgba(16, 185, 129, 0.08)',
    color: isEnabled ? '#ef4444' : '#10b981',
    border: 'none',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: '700',
    padding: '6px 12px',
    borderRadius: '10px',
    transition: 'background 0.2s ease',
  }),
  notificationDropdown: {
    position: 'absolute',
    top: '100%',
    left: '0',
    right: '0',
    marginTop: '12px',
    background: '#121215',
    border: '1px solid #1f1f24',
    borderRadius: '20px',
    boxShadow: '0 10px 30px rgba(0, 0, 0, 0.5)',
    zIndex: 1000,
    overflow: 'hidden',
  },
  dropdownHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 18px',
    borderBottom: '1px solid #1f1f24',
    fontWeight: '700',
    fontSize: '13px',
    color: '#10b981',
    background: 'rgba(16, 185, 129, 0.05)',
  },
  closeDropdownBtn: {
    background: 'none',
    border: 'none',
    color: '#10b981',
    cursor: 'pointer',
    fontSize: '14px',
    padding: '4px',
  },
  dropdownList: {
    maxHeight: '250px',
    overflowY: 'auto',
    padding: '8px 0',
  },
  dropdownItem: (isActive) => ({
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '10px 18px',
    transition: 'background 0.2s ease',
    background: isActive ? 'rgba(16, 185, 129, 0.06)' : 'transparent',
    borderBottom: '1px solid #1f1f24',
    cursor: 'pointer',
  }),
  dropdownItemDot: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    backgroundColor: '#10b981',
    flexShrink: 0,
  },
  dropdownItemText: {
    fontSize: '13px',
    color: '#ffffff',
    textAlign: 'left',
    lineHeight: '1.4',
  },
  dropdownEmpty: {
    padding: '20px',
    textAlign: 'center',
    color: '#a1a1aa',
    fontSize: '13px',
  },
};
