export const styles = {
  container: {
    width: '100%',
    alignSelf: 'stretch',
    boxSizing: 'border-box',
    minHeight: '100vh',
    padding: '24px 32px 40px 300px',
    background: '#f3f5f0',
    fontFamily: 'Plus Jakarta Sans, Inter, system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
    color: '#12241b',
  },
  header: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '14px',
    padding: '14px 20px',
    borderRadius: '24px',
    background: '#ffffff',
    border: '1px solid #e4e9e1',
    boxShadow: '0 4px 20px rgba(12, 52, 39, 0.03)',
  },
  logoSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    minWidth: 0,
  },
  logoBadge: {
    width: '40px',
    height: '40px',
    borderRadius: '12px',
    background: 'linear-gradient(135deg, #0c3427, #144837)',
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '20px',
    fontWeight: '800',
    boxShadow: '0 4px 12px rgba(12, 52, 39, 0.2)',
  },
  metaText: {
    color: '#697a70',
    fontSize: '14px',
    lineHeight: '1.85',
    display: 'inline-flex',
    flexWrap: 'wrap',
    gap: '0 10px',
  },
  navSection: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  navButton: {
    padding: '8px 18px',
    borderRadius: '999px',
    border: '1px solid transparent',
    background: 'transparent',
    color: '#697a70',
    fontWeight: '600',
    cursor: 'pointer',
    fontSize: '14px',
    transition: 'all 0.25s ease',
  },
  navButtonActive: {
    background: '#0c3427',
    border: '1px solid #0c3427',
    color: '#ffffff',
    boxShadow: '0 2px 8px rgba(12, 52, 39, 0.2)',
  },
  adminChip: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '7px 14px',
    borderRadius: '999px',
    background: '#ffffff',
    border: '1px solid #e4e9e1',
    color: '#12241b',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.02)',
  },
  adminAvatar: {
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #0c3427, #144837)',
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '12px',
    fontWeight: '800',
  },
  logoutButtonStyle: {
    padding: '8px 16px',
    borderRadius: '999px',
    border: '1px solid #e4e9e1',
    background: '#ffffff',
    color: '#dc2626',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'all 0.25s ease',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.02)',
  },
  mainContent: {
    width: '100%',
    maxWidth: 'none',
    margin: '24px 0 0',
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  titleSection: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    textAlign: 'left',
    flexWrap: 'wrap',
    gap: '16px',
    width: '100%',
  },
  title: {
    margin: 0,
    fontSize: '32px',
    fontWeight: '800',
    color: '#12241b',
    lineHeight: '1.1',
    maxWidth: '960px',
    width: '100%',
    letterSpacing: '-0.02em',
  },
  subTitleSection: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: '10px',
  },
  subTitle: {
    color: '#697a70',
    fontSize: '14px',
    fontWeight: '500',
  },
  countBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '46px',
    padding: '6px 14px',
    borderRadius: '999px',
    background: 'rgba(12, 52, 39, 0.08)',
    color: '#0c3427',
    fontWeight: '700',
    fontSize: '13px',
    boxShadow: 'inset 0 0 0 1px rgba(12, 52, 39, 0.15)',
  },
  controlsSection: {
    display: 'grid',
    gridTemplateColumns: '1fr',
    gap: '16px',
  },
  actionButtons: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  searchInput: {
    width: '100%',
    maxWidth: '300px',
    padding: '10px 18px',
    borderRadius: '999px',
    border: '1px solid #e4e9e1',
    background: '#ebefe8',
    color: '#12241b',
    fontSize: '14px',
    outline: 'none',
    boxSizing: 'border-box',
    boxShadow: '0 2px 6px rgba(0, 0, 0, 0.02)',
    transition: 'border-color 0.25s ease, box-shadow 0.25s ease',
  },
  selectDropdown: {
    padding: '10px 16px',
    borderRadius: '999px',
    border: '1px solid #e4e9e1',
    background: '#ffffff',
    color: '#12241b',
    fontSize: '14px',
    outline: 'none',
    cursor: 'pointer',
    boxShadow: '0 2px 6px rgba(0, 0, 0, 0.02)',
    transition: 'border-color 0.25s ease, box-shadow 0.25s ease',
  },
  statusSelectBorder: (status) => ({
    borderColor:
      status === 'Online' ? '#0c3427' :
      '#e4e9e1',
  }),
  enabledSelectBorder: (status) => ({
    borderColor:
      status === 'Enabled' ? '#0c3427' :
      '#e4e9e1',
  }),
  iconButton: {
    width: '40px',
    height: '40px',
    borderRadius: '12px',
    border: '1px solid #e4e9e1',
    background: '#ffffff',
    color: '#697a70',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.02)',
    transition: 'transform 0.2s ease, background-color 0.25s ease',
  },
  actionButton: {
    padding: '9px 18px',
    borderRadius: '999px',
    border: '1px solid #e4e9e1',
    background: '#ffffff',
    color: '#12241b',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.02)',
    transition: 'all 0.25s ease',
  },
  primaryActionButton: {
    marginLeft: 'auto',
    padding: '10px 24px',
    borderRadius: '999px',
    border: 'none',
    background: '#0c3427',
    color: '#ffffff',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
    boxShadow: '0 4px 14px rgba(12, 52, 39, 0.2)',
    transition: 'all 0.25s ease',
  },
  deleteSelectedBtn: {
    padding: '9px 18px',
    borderRadius: '999px',
    border: '1px solid rgba(220, 38, 38, 0.2)',
    background: 'rgba(220, 38, 38, 0.06)',
    color: '#dc2626',
    fontWeight: '700',
    cursor: 'pointer',
    boxShadow: 'none',
  },
  cancelButton: {
    padding: '9px 18px',
    borderRadius: '999px',
    border: '1px solid #e4e9e1',
    background: '#ffffff',
    color: '#697a70',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'all 0.25s ease',
  },
  paginationBar: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '22px 28px',
    borderBottom: '1px solid #e4e9e1',
    minWidth: 0,
  },
  selectALLButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '42px',
    height: '42px',
    borderRadius: '12px',
    background: '#f8faf6',
    border: '1px solid #e4e9e1',
    color: '#697a70',
  },
  checkbox: {
    width: '18px',
    height: '18px',
    borderRadius: '6px',
    border: '1px solid #c8d2c5',
    accentColor: '#0c3427',
  },
  paginationInfo: {
    color: '#697a70',
    fontSize: '14px',
    flex: '1 1 220px',
    minWidth: '180px',
  },
  paginationControls: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flex: '1 1 320px',
    minWidth: '220px',
  },
  pageSizeSelect: {
    width: '78px',
    padding: '8px 12px',
    borderRadius: '10px',
    border: '1px solid #e4e9e1',
    background: '#ffffff',
    color: '#12241b',
    fontSize: '14px',
    outline: 'none',
    cursor: 'pointer',
  },
  pageNavButton: {
    padding: '8px 16px',
    borderRadius: '10px',
    border: '1px solid #e4e9e1',
    background: '#ffffff',
    color: '#12241b',
    cursor: 'pointer',
    fontWeight: '700',
    transition: 'all 0.25s ease',
    minWidth: '96px',
    whiteSpace: 'nowrap',
  },
  pageNumber: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '36px',
    minWidth: '36px',
    height: '36px',
    padding: 0,
    borderRadius: '999px',
    border: '1px solid #e4e9e1',
    background: '#ffffff',
    color: '#697a70',
    cursor: 'pointer',
  },
  pageNumberActive: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '36px',
    minWidth: '36px',
    height: '36px',
    padding: 0,
    borderRadius: '999px',
    border: '1px solid #0c3427',
    background: '#0c3427',
    color: '#ffffff',
    fontWeight: '700',
  },
  paginationEllipsis: {
    minWidth: '28px',
    color: '#697a70',
    textAlign: 'center',
    fontWeight: '700',
  },
  assetPanel: {
    minHeight: '430px',
    borderRadius: '24px',
    background: '#ffffff',
    border: '1px solid #e4e9e1',
    boxShadow: '0 4px 20px rgba(12, 52, 39, 0.03)',
    overflow: 'hidden',
  },
  deviceList: {
    display: 'grid',
    gap: 0,
    minHeight: '268px',
  },
  deviceCard: {
    borderRadius: 0,
    background: 'transparent',
    boxShadow: 'none',
    border: 0,
    borderBottom: '1px solid #e4e9e1',
    overflow: 'hidden',
  },
  deviceHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '16px',
    minHeight: '88px',
    padding: '14px 28px',
  },
  deviceHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    flexWrap: 'wrap',
  },
  deviceNumber: {
    fontFamily: 'inherit',
    fontWeight: '700',
    color: '#0c3427',
    fontSize: '13px',
    minWidth: '28px',
  },
  deviceName: {
    fontWeight: '700',
    color: '#12241b',
    fontSize: '16px',
  },
  assetIdBadge: {
    width: '18px',
    height: '8px',
    padding: 0,
    borderRadius: '999px',
    background: 'rgba(12, 52, 39, 0.08)',
    color: '#0c3427',
    fontSize: 0,
    overflow: 'hidden',
  },
  badge: (status) => ({
    padding: '6px 14px',
    borderRadius: '999px',
    border: '1px solid transparent',
    background:
      status === 'Online' || status === 'Enabled' ? 'rgba(34, 134, 93, 0.12)' :
      '#ebefe8',
    color:
      status === 'Online' || status === 'Enabled' ? '#0c3427' :
      '#697a70',
    fontWeight: '700',
    fontSize: '12px',
  }),
  deviceHeaderRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap',
  },
  expandIcon: {
    cursor: 'pointer',
    width: '38px',
    height: '38px',
    padding: 0,
    borderRadius: '10px',
    color: '#697a70',
    transition: 'transform 0.2s ease',
    background: '#f8faf6',
    border: '1px solid #e4e9e1',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyState: {
    minHeight: '268px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#8e9e94',
    fontSize: '14px',
  },
  deviceDetails: {
    padding: '24px 28px',
    background: '#fcfdfa',
    borderTop: '1px solid #e4e9e1',
  },
  detailsHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '16px',
    marginBottom: '18px',
  },
  detailsTitle: {
    fontWeight: '700',
    color: '#12241b',
    fontSize: '16px',
  },
  detailsActions: {
    display: 'flex',
    gap: '10px',
    flexWrap: 'wrap',
  },
  saveButton: {
    padding: '10px 22px',
    borderRadius: '999px',
    border: 'none',
    background: '#0c3427',
    color: '#ffffff',
    fontWeight: '700',
    cursor: 'pointer',
    boxShadow: '0 4px 12px rgba(12, 52, 39, 0.2)',
  },
  editButton: {
    padding: '10px 22px',
    borderRadius: '999px',
    border: '1px solid #e4e9e1',
    background: '#ffffff',
    color: '#12241b',
    fontWeight: '700',
    cursor: 'pointer',
  },
  detailItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    minWidth: 0,
  },
  detailLabel: {
    fontSize: '13px',
    fontWeight: '700',
    color: '#697a70',
  },
  editInput: {
    width: '100%',
    padding: '12px 14px',
    borderRadius: '12px',
    border: '1px solid #e4e9e1',
    background: '#ffffff',
    color: '#12241b',
    outline: 'none',
  },
  detailValue: {
    color: '#12241b',
    fontSize: '14px',
  },
  mono: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  },
  section: {
    marginTop: '20px',
    borderRadius: '16px',
    background: '#ffffff',
    border: '1px solid #e4e9e1',
    boxShadow: 'none',
    padding: '20px',
  },
  sectionTitle: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    fontWeight: '700',
    color: '#12241b',
    fontSize: '15px',
    marginBottom: '16px',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  sectionGrid: {
    display: 'grid',
    gap: '18px',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
  },
  statusRow: {
    display: 'grid',
    gap: '16px',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    marginTop: '18px',
  },
  statusField: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  timestampBar: {
    marginTop: '20px',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
    alignItems: 'center',
  },
  timestampChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 16px',
    borderRadius: '999px',
    background: '#ffffff',
    color: '#697a70',
    fontSize: '13px',
    border: '1px solid #e4e9e1',
  },
  timestampSep: {
    width: '1px',
    height: '20px',
    background: '#e4e9e1',
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '18px',
    zIndex: 2000,
  },
  modal: {
    width: 'min(100%, 760px)',
    maxHeight: '88vh',
    overflowY: 'auto',
    background: '#ffffff',
    borderRadius: '24px',
    padding: '28px 30px',
    border: '1px solid #e4e9e1',
    boxShadow: '0 20px 48px rgba(12, 52, 39, 0.12)',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
  },
  modalTitle: {
    margin: 0,
    fontSize: '20px',
    fontWeight: '700',
    color: '#12241b',
  },
  modalBody: {
    width: '100%',
  },
  modalClose: {
    background: 'transparent',
    border: 'none',
    color: '#697a70',
    cursor: 'pointer',
    fontSize: '18px',
    width: '34px',
    height: '34px',
    borderRadius: '8px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '14px 16px',
  },
  modalField: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  modalLabel: {
    fontSize: '12px',
    fontWeight: '700',
    color: '#697a70',
  },
  modalInput: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: '10px',
    border: '1px solid #e4e9e1',
    background: '#ebefe8',
    color: '#12241b',
    fontSize: '14px',
    outline: 'none',
    boxSizing: 'border-box',
  },
  modalSelect: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: '10px',
    border: '1px solid #e4e9e1',
    background: '#ffffff',
    color: '#12241b',
    fontSize: '14px',
    outline: 'none',
    cursor: 'pointer',
    boxSizing: 'border-box',
  },
  modalFooter: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: '10px',
  },
  modalCancel: {
    padding: '10px 20px',
    borderRadius: '999px',
    border: '1px solid #e4e9e1',
    background: '#ffffff',
    color: '#697a70',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
  },
  modalCreate: {
    padding: '10px 24px',
    borderRadius: '999px',
    border: 'none',
    background: '#0c3427',
    color: '#ffffff',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
    boxShadow: '0 4px 14px rgba(12, 52, 39, 0.2)',
  },
  viewSelectedBtn: {
    padding: '9px 18px',
    borderRadius: '999px',
    border: '1px solid rgba(12, 52, 39, 0.18)',
    background: 'rgba(12, 52, 39, 0.08)',
    color: '#0c3427',
    fontWeight: '700',
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(12, 52, 39, 0.05)',
    transition: 'all 0.25s ease',
  },
  verifyModal: {
    width: 'min(100%, 420px)',
    background: '#ffffff',
    borderRadius: '24px',
    padding: '28px 30px',
    border: '1px solid #e4e9e1',
    boxShadow: '0 20px 48px rgba(12, 52, 39, 0.15)',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    position: 'relative',
  },
  detailsModalOverlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    backdropFilter: 'blur(8px)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '24px 18px',
    zIndex: 2000,
  },
  detailsModal: {
    width: 'min(100%, 820px)',
    maxHeight: '90vh',
    overflowY: 'auto',
    background: '#ffffff',
    borderRadius: '24px',
    padding: '32px 34px',
    border: '1px solid #e4e9e1',
    boxShadow: '0 20px 50px rgba(12, 52, 39, 0.12)',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  bulkModal: {
    width: 'min(100%, 1200px)',
    maxHeight: '90vh',
    overflowY: 'auto',
    background: '#f3f5f0',
    borderRadius: '28px',
    padding: '32px 34px',
    border: '1px solid #e4e9e1',
    boxShadow: '0 20px 50px rgba(12, 52, 39, 0.15)',
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  bulkGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(360px, 1fr))',
    gap: '20px',
    padding: '10px 0',
  },
  bulkCard: {
    borderRadius: '20px',
    background: '#ffffff',
    border: '1px solid #e4e9e1',
    boxShadow: '0 4px 20px rgba(12, 52, 39, 0.04)',
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    position: 'relative',
    overflow: 'hidden',
    minHeight: '400px',
  },
  lockOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'rgba(255, 255, 255, 0.95)',
    backdropFilter: 'blur(8px)',
    zIndex: 100,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '16px',
    padding: '24px',
    textAlign: 'center',
  },
  lockIcon: {
    width: '56px',
    height: '56px',
    borderRadius: '50%',
    background: 'rgba(12, 52, 39, 0.08)',
    color: '#0c3427',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '24px',
    boxShadow: '0 4px 14px rgba(12, 52, 39, 0.1)',
  },
  lockInput: {
    width: '100%',
    maxWidth: '260px',
    padding: '12px 16px',
    borderRadius: '12px',
    border: '1px solid #e4e9e1',
    background: '#ebefe8',
    color: '#12241b',
    fontSize: '14px',
    outline: 'none',
    boxSizing: 'border-box',
    textAlign: 'center',
    transition: 'all 0.2s ease',
  },
  lockError: {
    color: '#dc2626',
    fontSize: '12px',
    fontWeight: '600',
    marginTop: '-4px',
  },
  unlockButton: {
    padding: '12px 24px',
    borderRadius: '999px',
    border: 'none',
    background: '#0c3427',
    color: '#ffffff',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
    boxShadow: '0 4px 14px rgba(12, 52, 39, 0.2)',
    transition: 'all 0.2s ease',
  },
};
