export const styles = {
  importContainer: {
    width: '100%',
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '32px',
    boxSizing: 'border-box',
    background: '#f3f5f0',
    color: '#12241b',
    fontFamily: 'Inter, system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
  },
  importContent: {
    width: '100%',
    maxWidth: '1160px',
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    background: '#ffffff',
    borderRadius: '24px',
    padding: '30px',
    boxShadow: '0 4px 20px rgba(12, 52, 39, 0.04)',
    border: '1px solid #e4e9e1',
  },
  importInstructions: {
    backgroundColor: '#f8faf6',
    padding: '26px',
    borderRadius: '20px',
    border: '1px solid #e4e9e1',
  },
  importInstructionsHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '18px',
    marginBottom: '28px',
  },
  importCsvBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '56px',
    height: '56px',
    backgroundColor: '#ebefe8',
    color: '#0c3427',
    fontWeight: '700',
    fontSize: '14px',
    borderRadius: '16px',
    border: '1px solid #dbe2d8',
    boxShadow: '0 2px 8px rgba(12, 52, 39, 0.05)',
  },
  importInstructionsTitle: {
    margin: 0,
    fontSize: '22px',
    fontWeight: '700',
    color: '#12241b',
  },
  importInstructionsSubtitle: {
    margin: 0,
    fontSize: '14px',
    color: '#697a70',
  },
  importFieldsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: '14px',
  },
  importFieldCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '16px 18px',
    backgroundColor: '#ffffff',
    border: '1px solid #e4e9e1',
    borderRadius: '16px',
    boxShadow: '0 2px 8px rgba(12, 52, 39, 0.04)',
  },
  importFieldCardRequired: {
    backgroundColor: 'rgba(34, 134, 93, 0.06)',
    borderColor: 'rgba(34, 134, 93, 0.2)',
  },
  importFieldIconCircle: {
    width: '38px',
    height: '38px',
    borderRadius: '50%',
    backgroundColor: '#ebefe8',
    color: '#0c3427',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    border: '1px solid #dbe2d8',
  },
  importFieldLabel: {
    fontSize: '13px',
    fontWeight: '700',
    color: '#12241b',
    letterSpacing: '0.06em',
    flex: 1,
    textAlign: 'left',
  },
  importFieldNum: {
    fontSize: '12px',
    color: '#22865d',
    fontWeight: '700',
  },
  importDropZone: {
    border: '2px dashed #c0cbbd',
    borderRadius: '22px',
    padding: '44px 30px',
    textAlign: 'center',
    backgroundColor: '#f8faf6',
    transition: 'all 0.3s ease',
    minHeight: '260px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    boxShadow: 'none',
  },
  importDropZoneDragging: {
    borderColor: '#0c3427',
    backgroundColor: 'rgba(12, 52, 39, 0.04)',
    transform: 'translateY(-1px)',
  },
  importDropZoneFileLoaded: {
    borderColor: '#22865d',
    borderStyle: 'solid',
    backgroundColor: '#ffffff',
  },
  importDropIconCircle: {
    width: '72px',
    height: '72px',
    borderRadius: '50%',
    backgroundColor: '#ebefe8',
    color: '#0c3427',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '14px',
    boxShadow: '0 4px 12px rgba(12, 52, 39, 0.08)',
  },
  importDropText: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#12241b',
    margin: '0',
  },
  importDropSubtext: {
    color: '#697a70',
    margin: '10px 0 0 0',
    fontSize: '14px',
  },
  importBrowseButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '12px 28px',
    borderRadius: '999px',
    backgroundColor: '#0c3427',
    color: '#ffffff',
    border: 'none',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '700',
    marginTop: '16px',
    boxShadow: '0 4px 14px rgba(12, 52, 39, 0.2)',
  },
  importFileInput: {
    display: 'none',
  },
  importFileInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    padding: '18px 20px',
    backgroundColor: '#f8faf6',
    borderRadius: '22px',
    width: '100%',
    maxWidth: '620px',
    border: '1px solid #e4e9e1',
    boxShadow: '0 2px 8px rgba(12, 52, 39, 0.04)',
  },
  importFileIconBox: {
    width: '48px',
    height: '48px',
    backgroundColor: '#ebefe8',
    borderRadius: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1px solid #dbe2d8',
    color: '#0c3427',
    flexShrink: 0,
  },
  importFileName: {
    margin: 0,
    fontSize: '15px',
    fontWeight: '700',
    color: '#12241b',
  },
  importFileSize: {
    color: '#697a70',
    fontSize: '12px',
    margin: '4px 0 0 0',
  },
  importFileCheckmark: {
    width: '34px',
    height: '34px',
    borderRadius: '50%',
    backgroundColor: '#22865d',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '14px',
    fontWeight: '700',
    flexShrink: 0,
  },
  importRemoveFile: {
    background: '#ebefe8',
    border: '1px solid #dbe2d8',
    color: '#697a70',
    cursor: 'pointer',
    fontSize: '16px',
    marginLeft: 'auto',
    padding: '8px 10px',
    borderRadius: '14px',
  },
  importError: {
    backgroundColor: 'rgba(217, 83, 79, 0.08)',
    border: '1px solid rgba(217, 83, 79, 0.18)',
    color: '#c9302c',
    padding: '14px 16px',
    borderRadius: '18px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontSize: '14px',
  },
  importPreview: {
    backgroundColor: '#ffffff',
    borderRadius: '20px',
    padding: '24px',
    border: '1px solid #e4e9e1',
    boxShadow: '0 4px 20px rgba(12, 52, 39, 0.04)',
  },
  importPreviewHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '18px',
    paddingBottom: '14px',
    borderBottom: '1px solid #e4e9e1',
  },
  importPreviewTitle: {
    margin: 0,
    fontSize: '18px',
    fontWeight: '700',
    color: '#12241b',
  },
  importPreviewCount: {
    color: '#697a70',
    fontSize: '13px',
  },
  importTableWrapper: {
    overflowX: 'auto',
    marginBottom: '22px',
    borderRadius: '20px',
    border: '1px solid #e4e9e1',
  },
  importTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '13px',
  },
  importTableHeader: {
    backgroundColor: '#f8faf6',
    padding: '14px 16px',
    textAlign: 'left',
    fontWeight: '700',
    fontSize: '12px',
    color: '#697a70',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    borderBottom: '1px solid #e4e9e1',
    whiteSpace: 'nowrap',
  },
  importTableCell: {
    padding: '14px 16px',
    borderBottom: '1px solid #e4e9e1',
    color: '#12241b',
    fontSize: '13px',
    textAlign: 'left',
  },
  importPreviewActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
    justifyContent: 'flex-end',
    paddingTop: '4px',
  },
  importConfirmButton: {
    padding: '12px 26px',
    background: '#0c3427',
    color: '#ffffff',
    border: 'none',
    borderRadius: '999px',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
    boxShadow: '0 4px 14px rgba(12, 52, 39, 0.2)',
  },
  importClearButton: {
    padding: '12px 26px',
    backgroundColor: '#ebefe8',
    color: '#12241b',
    border: '1px solid #dbe2d8',
    borderRadius: '999px',
    fontSize: '14px',
    cursor: 'pointer',
    boxShadow: 'none',
  },
  importSampleLink: {
    color: '#0c3427',
    textDecoration: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    fontSize: '14px',
    fontWeight: '700',
    padding: '10px 18px',
    backgroundColor: '#ebefe8',
    borderRadius: '999px',
    border: '1px solid #dbe2d8',
    transition: 'all 0.25s ease',
  },
  importDropHints: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginTop: '12px',
    fontSize: '12px',
    color: '#697a70',
  },
  importDropHintDot: {
    color: '#22865d',
  },
};
