export const styles = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '24px',
    background: '#f3f5f0',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    color: '#12241b',
  },
  card: {
    width: 'min(100%, 500px)',
    background: '#ffffff',
    borderRadius: '28px',
    border: '1px solid #e4e9e1',
    boxShadow: '0 8px 32px rgba(12, 52, 39, 0.06)',
    padding: '44px 40px',
    display: 'flex',
    flexDirection: 'column',
    gap: '22px',
  },
  header: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    marginBottom: '8px',
  },
  title: {
    margin: 0,
    fontSize: '28px',
    lineHeight: '1.2',
    fontWeight: '800',
    color: '#12241b',
    letterSpacing: '-0.02em',
  },
  subtitle: {
    margin: 0,
    fontSize: '14px',
    lineHeight: '1.6',
    color: '#697a70',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  label: {
    fontWeight: '600',
    fontSize: '13px',
    color: '#12241b',
    textAlign: 'left',
  },
  input: {
    width: '100%',
    padding: '14px 18px',
    borderRadius: '16px',
    border: '1px solid #dbe2d8',
    backgroundColor: '#ebefe8',
    color: '#12241b',
    fontSize: '14px',
    outline: 'none',
    boxSizing: 'border-box',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
  },
  button: {
    width: '100%',
    borderRadius: '999px',
    padding: '15px 20px',
    border: 'none',
    background: '#0c3427',
    color: '#ffffff',
    fontSize: '15px',
    fontWeight: '700',
    letterSpacing: '0.02em',
    cursor: 'pointer',
    boxShadow: '0 4px 14px rgba(12, 52, 39, 0.2)',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease',
  },
  buttonSecondary: {
    width: '100%',
    borderRadius: '999px',
    padding: '15px 20px',
    border: '1px solid #dbe2d8',
    backgroundColor: '#ebefe8',
    color: '#12241b',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease, transform 0.2s ease',
  },
  noteText: {
    textAlign: 'center',
    marginTop: '12px',
    fontSize: '14px',
    color: '#697a70',
    lineHeight: '1.6',
  },
  link: {
    color: '#0c3427',
    fontWeight: '700',
    textDecoration: 'none',
  },
};
