export const styles = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '24px',
    background: '#09090b',
    fontFamily: 'Inter, system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
    color: '#ffffff',
  },
  card: {
    width: 'min(100%, 520px)',
    background: '#121215',
    borderRadius: '24px',
    border: '1px solid #1f1f24',
    boxShadow: '0 20px 48px rgba(0, 0, 0, 0.4)',
    padding: '40px 36px',
    display: 'flex',
    flexDirection: 'column',
    gap: '22px',
  },
  header: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginBottom: '8px',
  },
  title: {
    margin: 0,
    fontSize: '30px',
    lineHeight: '1.1',
    fontWeight: '800',
    color: '#ffffff',
  },
  subtitle: {
    margin: 0,
    fontSize: '15px',
    lineHeight: '1.8',
    color: '#a1a1aa',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  label: {
    fontWeight: '600',
    fontSize: '13px',
    color: '#ffffff',
    textAlign: 'left',
  },
  input: {
    width: '100%',
    padding: '16px 18px',
    borderRadius: '16px',
    border: '1px solid #27272a',
    backgroundColor: '#18181c',
    color: '#ffffff',
    fontSize: '15px',
    outline: 'none',
    boxSizing: 'border-box',
    transition: 'border-color 0.25s ease, box-shadow 0.25s ease',
  },
  button: {
    width: '100%',
    borderRadius: '999px',
    padding: '16px 20px',
    border: 'none',
    background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    color: '#ffffff',
    fontSize: '15px',
    fontWeight: '700',
    letterSpacing: '0.08em',
    cursor: 'pointer',
    boxShadow: '0 12px 24px rgba(16, 185, 129, 0.25)',
    transition: 'transform 0.25s ease, box-shadow 0.25s ease',
  },
  buttonSecondary: {
    width: '100%',
    borderRadius: '999px',
    padding: '16px 20px',
    border: '1px solid #27272a',
    backgroundColor: '#18181c',
    color: '#ffffff',
    fontSize: '15px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'background-color 0.25s ease, transform 0.25s ease',
  },
  noteText: {
    textAlign: 'center',
    marginTop: '16px',
    fontSize: '14px',
    color: '#a1a1aa',
    lineHeight: '1.7',
  },
  link: {
    color: '#10b981',
    fontWeight: '700',
    textDecoration: 'none',
  },
};
