export const styles = {
  container: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100vh',
    padding: '24px',
    background: '#09090b',
    fontFamily: 'Inter, system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
    color: '#ffffff',
  },
  card: {
    width: 'min(100%, 780px)',
    background: '#121215',
    borderRadius: '24px',
    border: '1px solid #1f1f24',
    boxShadow: '0 20px 48px rgba(0, 0, 0, 0.4)',
    padding: '38px 36px',
    display: 'flex',
    flexDirection: 'column',
    gap: '22px',
  },
  header: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginBottom: '4px',
  },
  title: {
    margin: 0,
    fontSize: '30px',
    lineHeight: '1.1',
    fontWeight: '800',
    color: '#ffffff',
  },
  subtitle: {
    margin: 0,
    fontSize: '15px',
    lineHeight: '1.75',
    color: '#a1a1aa',
  },
  rowGroup: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '18px',
  },
  column: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    minWidth: 0,
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  label: {
    fontWeight: '600',
    fontSize: '13px',
    color: '#ffffff',
    textAlign: 'left',
  },
  input: {
    width: '100%',
    padding: '16px 18px',
    borderRadius: '16px',
    border: '1px solid #27272a',
    backgroundColor: '#18181c',
    fontSize: '15px',
    color: '#ffffff',
    outline: 'none',
    boxSizing: 'border-box',
    transition: 'border-color 0.25s ease, box-shadow 0.25s ease',
  },
  select: {
    width: '100%',
    padding: '16px 18px',
    borderRadius: '16px',
    border: '1px solid #27272a',
    backgroundColor: '#18181c',
    fontSize: '15px',
    color: '#ffffff',
    outline: 'none',
    appearance: 'none',
    boxSizing: 'border-box',
  },
  button: {
    width: '100%',
    borderRadius: '999px',
    padding: '16px 20px',
    border: 'none',
    background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    color: '#ffffff',
    fontSize: '15px',
    fontWeight: '700',
    letterSpacing: '0.08em',
    cursor: 'pointer',
    boxShadow: '0 12px 24px rgba(16, 185, 129, 0.25)',
    transition: 'transform 0.25s ease, box-shadow 0.25s ease',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalCard: {
    width: 'min(100%, 420px)',
    background: '#121215',
    borderRadius: '24px',
    border: '1px solid #1f1f24',
    boxShadow: '0 24px 60px rgba(0, 0, 0, 0.5)',
    padding: '34px 28px',
  },
  modalButtonGroup: {
    display: 'flex',
    gap: '14px',
    marginTop: '16px',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  smallButtonPrimary: {
    width: 'auto',
    padding: '14px 28px',
    fontSize: '14px',
    fontWeight: '700',
  },
  smallButtonCancel: {
    width: 'auto',
    padding: '14px 28px',
    fontSize: '14px',
    fontWeight: '700',
    backgroundColor: '#18181c',
    color: '#ffffff',
    border: '1px solid #27272a',
  },
  noteText: {
    textAlign: 'center',
    marginTop: '18px',
    fontSize: '14px',
    color: '#a1a1aa',
    lineHeight: '1.75',
  },
  link: {
    color: '#10b981',
    fontWeight: '700',
    textDecoration: 'none',
  },
};
