export const styles = {
  container: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100vh',
    padding: '24px',
    background: '#f3f5f0',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    color: '#12241b',
  },
  card: {
    width: 'min(100%, 780px)',
    background: '#ffffff',
    borderRadius: '28px',
    border: '1px solid #e4e9e1',
    boxShadow: '0 8px 32px rgba(12, 52, 39, 0.06)',
    padding: '38px 36px',
    display: 'flex',
    flexDirection: 'column',
    gap: '22px',
  },
  header: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    marginBottom: '4px',
  },
  title: {
    margin: 0,
    fontSize: '28px',
    lineHeight: '1.2',
    fontWeight: '800',
    color: '#12241b',
    letterSpacing: '-0.02em',
  },
  subtitle: {
    margin: 0,
    fontSize: '14px',
    lineHeight: '1.6',
    color: '#697a70',
  },
  rowGroup: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '18px',
  },
  column: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    minWidth: 0,
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  label: {
    fontWeight: '600',
    fontSize: '13px',
    color: '#12241b',
    textAlign: 'left',
  },
  input: {
    width: '100%',
    padding: '14px 18px',
    borderRadius: '16px',
    border: '1px solid #dbe2d8',
    backgroundColor: '#ebefe8',
    fontSize: '14px',
    color: '#12241b',
    outline: 'none',
    boxSizing: 'border-box',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
  },
  select: {
    width: '100%',
    padding: '14px 18px',
    borderRadius: '16px',
    border: '1px solid #dbe2d8',
    backgroundColor: '#ebefe8',
    fontSize: '14px',
    color: '#12241b',
    outline: 'none',
    appearance: 'none',
    boxSizing: 'border-box',
  },
  button: {
    width: '100%',
    borderRadius: '999px',
    padding: '15px 20px',
    border: 'none',
    background: '#0c3427',
    color: '#ffffff',
    fontSize: '15px',
    fontWeight: '700',
    letterSpacing: '0.02em',
    cursor: 'pointer',
    boxShadow: '0 4px 14px rgba(12, 52, 39, 0.2)',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(12, 52, 39, 0.4)',
    backdropFilter: 'blur(6px)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalCard: {
    width: 'min(100%, 420px)',
    background: '#ffffff',
    borderRadius: '24px',
    border: '1px solid #e4e9e1',
    boxShadow: '0 20px 50px rgba(12, 52, 39, 0.15)',
    padding: '34px 28px',
  },
  modalButtonGroup: {
    display: 'flex',
    gap: '14px',
    marginTop: '16px',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  smallButtonPrimary: {
    width: 'auto',
    padding: '12px 28px',
    fontSize: '14px',
    fontWeight: '700',
    backgroundColor: '#0c3427',
    color: '#ffffff',
    border: 'none',
    borderRadius: '999px',
    boxShadow: '0 4px 14px rgba(12, 52, 39, 0.2)',
    cursor: 'pointer',
  },
  smallButtonCancel: {
    width: 'auto',
    padding: '12px 28px',
    fontSize: '14px',
    fontWeight: '700',
    backgroundColor: '#ebefe8',
    color: '#12241b',
    border: '1px solid #dbe2d8',
    borderRadius: '999px',
    cursor: 'pointer',
  },
  noteText: {
    textAlign: 'center',
    marginTop: '16px',
    fontSize: '14px',
    color: '#697a70',
    lineHeight: '1.6',
  },
  link: {
    color: '#0c3427',
    fontWeight: '700',
    textDecoration: 'none',
  },
};
