export const styles = {
  container: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100vh',
    padding: '24px',
    background: 'radial-gradient(circle at 18% 10%, rgba(255, 112, 67, 0.14), transparent 32%), linear-gradient(135deg, #f7f7f5 0%, #eeeeec 100%)',
    fontFamily: 'Inter, system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
    color: '#181816',
  },
  card: {
    width: 'min(100%, 780px)',
    background: '#ffffff',
    borderRadius: '24px',
    border: '1px solid rgba(24, 24, 22, 0.06)',
    boxShadow: '0 32px 74px rgba(24, 24, 22, 0.10)',
    padding: '38px 36px',
    display: 'flex',
    flexDirection: 'column',
    gap: '22px',
  },
  header: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginBottom: '4px',
  },
  title: {
    margin: 0,
    fontSize: '30px',
    lineHeight: '1.1',
    fontWeight: '800',
    color: '#181816',
  },
  subtitle: {
    margin: 0,
    fontSize: '15px',
    lineHeight: '1.75',
    color: '#70737b',
  },
  rowGroup: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '18px',
  },
  column: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    minWidth: 0,
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  label: {
    fontWeight: '600',
    fontSize: '13px',
    color: '#2d2d2a',
  },
  input: {
    width: '100%',
    padding: '16px 18px',
    borderRadius: '16px',
    border: '1px solid #e6e6e3',
    backgroundColor: '#fbfbfa',
    fontSize: '15px',
    color: '#181816',
    outline: 'none',
    boxSizing: 'border-box',
    boxShadow: 'inset 0 1px 4px rgba(24, 24, 22, 0.04)',
    transition: 'border-color 0.25s ease, box-shadow 0.25s ease',
  },
  select: {
    width: '100%',
    padding: '16px 18px',
    borderRadius: '16px',
    border: '1px solid #e6e6e3',
    backgroundColor: '#fbfbfa',
    fontSize: '15px',
    color: '#181816',
    outline: 'none',
    appearance: 'none',
    boxSizing: 'border-box',
    boxShadow: 'inset 0 1px 4px rgba(24, 24, 22, 0.04)',
  },
  button: {
    width: '100%',
    borderRadius: '999px',
    padding: '16px 20px',
    border: 'none',
    background: 'linear-gradient(135deg, #ff7043 0%, #f4511e 100%)',
    color: '#ffffff',
    fontSize: '15px',
    fontWeight: '700',
    letterSpacing: '0.08em',
    cursor: 'pointer',
    boxShadow: '0 18px 34px rgba(244, 81, 30, 0.22)',
    transition: 'transform 0.25s ease, box-shadow 0.25s ease',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(24, 24, 22, 0.32)',
    backdropFilter: 'blur(6px)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalCard: {
    width: 'min(100%, 420px)',
    background: '#ffffff',
    borderRadius: '24px',
    border: '1px solid rgba(24, 24, 22, 0.08)',
    boxShadow: '0 24px 60px rgba(24, 24, 22, 0.16)',
    padding: '34px 28px',
  },
  modalButtonGroup: {
    display: 'flex',
    gap: '14px',
    marginTop: '16px',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  smallButtonPrimary: {
    width: 'auto',
    padding: '14px 28px',
    fontSize: '14px',
    fontWeight: '700',
  },
  smallButtonCancel: {
    width: 'auto',
    padding: '14px 28px',
    fontSize: '14px',
    fontWeight: '700',
    backgroundColor: '#181816',
    color: '#ffffff',
    border: '1px solid #181816',
  },
  noteText: {
    textAlign: 'center',
    marginTop: '18px',
    fontSize: '14px',
    color: '#70737b',
    lineHeight: '1.75',
  },
  link: {
    color: '#f4511e',
    fontWeight: '700',
    textDecoration: 'none',
  },
};
