export const styles = {
  container: {
    minHeight: '100vh',
    background: '#f3f4f6',
    fontFamily: "'Montserrat', sans-serif",
    padding: '0',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '24px 40px',
    background: '#fff',
    borderBottom: '1px solid #e5e7eb',
  },
  profileSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
  },
  avatarCircle: {
    width: '56px',
    height: '56px',
    borderRadius: '50%',
    background: '#1a1a1a',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '22px',
    fontWeight: '700',
  },
  username: {
    fontWeight: '700',
    fontSize: '18px',
    color: '#111',
  },
  empId: {
    fontSize: '13px',
    color: '#888',
    marginTop: '2px',
  },
  notificationBar: {
    background: '#d1d5db',
    borderRadius: '14px',
    padding: '18px 60px',
    fontSize: '15px',
    color: '#444',
    fontWeight: '500',
  },
  joiningInfo: {
    textAlign: 'right',
    fontSize: '14px',
    color: '#555',
    lineHeight: '1.7',
  },
  backBtn: {
    margin: '18px 40px 0',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '14px',
    color: '#555',
    fontWeight: '600',
    padding: '6px 0',
  },
  mainGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '32px',
    padding: '24px 40px 40px',
  },
  devicesPanel: {
    background: '#d1d5db',
    borderRadius: '14px',
    padding: '24px',
    minHeight: '200px',
  },
  devicesPanelTitle: {
    fontWeight: '700',
    fontSize: '14px',
    letterSpacing: '0.08em',
    color: '#333',
    marginBottom: '16px',
  },
  noDevices: {
    color: '#888',
    fontSize: '13px',
  },
  deviceRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '10px 0',
    borderBottom: '1px solid rgba(0,0,0,0.08)',
    fontSize: '13px',
  },
  deviceRowId: {
    color: '#888',
    fontWeight: '600',
    minWidth: '24px',
  },
  deviceRowName: {
    fontWeight: '700',
    color: '#111',
    flex: 1,
  },
  deviceRowAsset: {
    color: '#555',
    fontSize: '12px',
    background: '#e5e7eb',
    borderRadius: '6px',
    padding: '2px 8px',
  },
  deviceRowStatus: {
    fontSize: '12px',
    fontWeight: '600',
  },
  messagePanel: {
    background: '#111',
    borderRadius: '18px',
    padding: '18px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    minHeight: '400px',
  },
  searchInput: {
    width: '100%',
    padding: '12px 18px',
    borderRadius: '30px',
    border: 'none',
    background: '#fff',
    fontSize: '14px',
    outline: 'none',
    boxSizing: 'border-box',
  },
  chatBox: {
    flex: 1,
    background: '#000',
    borderRadius: '10px',
    minHeight: '260px',
  },
  messageInput: {
    width: '100%',
    padding: '12px 18px',
    borderRadius: '30px',
    border: 'none',
    background: '#fff',
    fontSize: '14px',
    outline: 'none',
    boxSizing: 'border-box',
  },
};