export const styles = {
  container: {
    fontFamily: "'Montserrat', sans-serif",
    background: 'transparent',
    minHeight: '100vh',
    padding: '24px 40px 24px 300px', // Added 300px padding left for the sidebar
    color: '#111015',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '18px 22px',
    border: '1px solid #eef0f5',
    borderRadius: '24px',
    background: '#ffffff',
    boxShadow: '0 8px 30px rgba(0, 0, 0, 0.04)',
    marginBottom: '30px',
  },
  logoSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
  },
  logoBox: {
    fontSize: '28px',
    fontWeight: '700',
    color: '#111015',
  },
  metaText: {
    fontSize: '13px',
    color: '#64748b',
  },
  navSection: {
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
  },
  navButtonActive: {
    padding: '8px 20px',
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
    border: '1px solid rgba(16, 185, 129, 0.25)',
    color: '#10b981',
    fontWeight: '600',
    fontSize: '14px',
    cursor: 'pointer',
    borderRadius: '999px',
    transition: 'all 0.2s',
  },
  navButtonAction: {
    padding: '8px 20px',
    background: 'linear-gradient(135deg, #34d399, #10b981)',
    border: 'none',
    color: '#ffffff',
    fontWeight: '600',
    fontSize: '14px',
    cursor: 'pointer',
    borderRadius: '999px',
    transition: 'all 0.2s',
    boxShadow: '0 8px 16px rgba(16, 185, 129, 0.2)',
  },
  mainContent: {
    maxWidth: '1320px',
    margin: '0 auto',
  },
  titleSection: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginBottom: '20px',
    gap: '16px',
  },
  controlsSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    marginBottom: '20px',
  },
  title: {
    fontSize: '28px',
    fontWeight: '700',
    color: '#111015',
    marginBottom: '10px',
  },
  subTitleSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  subTitle: {
    fontSize: '16px',
    color: '#64748b',
    fontWeight: '500',
  },
  countBadge: {
    background: 'rgba(16, 185, 129, 0.08)',
    color: '#10b981',
    padding: '4px 12px',
    borderRadius: '999px',
    fontSize: '13px',
    fontWeight: '600',
    border: '1px solid rgba(16, 185, 129, 0.25)',
  },
  actionButtons: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    width: '100%',
  },
  searchInput: {
    padding: '8px 16px',
    borderRadius: '999px',
    border: '1px solid #e2e8f0',
    backgroundColor: '#ffffff',
    color: '#111015',
    fontSize: '14px',
    minWidth: '200px',
    width: '220px',
    outline: 'none',
    transition: 'border-color 0.2s',
  },
  iconButton: {
    padding: '8px 12px',
    backgroundColor: '#ffffff',
    color: '#111015',
    border: '1px solid #e2e8f0',
    borderRadius: '16px',
    fontSize: '20px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s',
    width: '38px',
    height: '38px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButton: {
    padding: '8px 16px',
    backgroundColor: '#ffffff',
    color: '#111015',
    border: '1px solid #e2e8f0',
    borderRadius: '999px',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  deviceList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  deviceCard: {
    backgroundColor: '#ffffff',
    borderRadius: '24px',
    boxShadow: '0 8px 30px rgba(0, 0, 0, 0.04)',
    border: '1px solid #eef0f5',
    overflow: 'hidden',
    transition: 'all 0.3s ease',
  },
  deviceHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '18px 20px',
    transition: 'background-color 0.2s',
  },
  deviceHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
    flexWrap: 'wrap',
  },
  checkbox: {
    width: '18px',
    height: '18px',
    cursor: 'pointer',
    accentColor: '#6366f1',
  },
  deviceNumber: {
    fontWeight: '600',
    color: '#94a3b8',
    fontSize: '14px',
    minWidth: '30px',
  },
  deviceName: {
    fontWeight: '600',
    fontSize: '16px',
    color: '#111015',
  },
  assetIdBadge: {
    backgroundColor: 'rgba(99, 102, 241, 0.08)',
    padding: '4px 12px',
    borderRadius: '12px',
    fontSize: '12px',
    color: '#6366f1',
    fontWeight: '500',
  },
  deviceHeaderRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
  },
  expandIcon: {
    fontSize: '14px',
    color: '#94a3b8',
    fontWeight: '600',
    cursor: 'pointer',
    padding: '5px 10px',
    borderRadius: '14px',
    transition: 'background-color 0.2s',
    ':hover': {
      backgroundColor: 'rgba(0, 0, 0, 0.05)',
    }
  },
  deviceDetails: {
    padding: '20px',
    borderTop: '1px solid #eef0f5',
    backgroundColor: '#f8fafc',
  },
  detailsHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
    paddingBottom: '12px',
    borderBottom: '1px solid #eef0f5',
  },
  detailsTitle: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#111015',
  },
  detailsActions: {
    display: 'flex',
    gap: '10px',
  },
  editButton: {
    padding: '6px 16px',
    backgroundColor: '#ffffff',
    color: '#111015',
    border: '1px solid #cbd5e1',
    borderRadius: '999px',
    fontSize: '13px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  saveButton: {
    padding: '6px 16px',
    background: 'linear-gradient(135deg, #6366f1, #a855f7)',
    color: '#ffffff',
    border: 'none',
    borderRadius: '999px',
    fontSize: '13px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.2s',
    boxShadow: '0 4px 12px rgba(99, 102, 241, 0.25)',
  },
  cancelButton: {
    padding: '6px 16px',
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    color: '#ef4444',
    border: '1px solid rgba(239, 68, 68, 0.25)',
    borderRadius: '999px',
    fontSize: '13px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  detailsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
    gap: '16px',
  },
  detailItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  detailLabel: {
    fontSize: '11px',
    fontWeight: '600',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  detailValue: {
    fontSize: '14px',
    color: '#111015',
    wordBreak: 'break-word',
    fontWeight: '500',
  },
  editInput: {
    padding: '6px 8px',
    borderRadius: '14px',
    border: '1px solid #cbd5e1',
    fontSize: '14px',
    outline: 'none',
    backgroundColor: '#ffffff',
    color: '#111015',
  },
  selectDropdown: {
    padding: '6px 10px',
    borderRadius: '14px',
    border: '1px solid #cbd5e1',
    backgroundColor: '#ffffff',
    fontSize: '13px',
    cursor: 'pointer',
    width: '140px',       // fixed width — add this
    minWidth: '140px',    // keep this too
    maxWidth: '140px',    // add this
    color: '#111015',
    fontWeight: '500',
    transition: 'border-color 0.2s',
  },
  badge: (status) => {
    const colors = {
        Online:   { bg: 'rgba(34, 197, 94, 0.12)', color: '#22c55e' },
        Warning:  { bg: 'rgba(245, 158, 11, 0.12)', color: '#d97706' },
        Error:    { bg: 'rgba(239, 68, 68, 0.12)', color: '#ef4444' },
        Offline:  { bg: 'rgba(100, 116, 139, 0.12)', color: '#64748b' },
        Enabled:  { bg: 'rgba(34, 197, 94, 0.12)', color: '#22c55e' },
        Disabled: { bg: 'rgba(100, 116, 139, 0.12)', color: '#64748b' },
        Unknown:  { bg: 'rgba(100, 116, 139, 0.12)', color: '#64748b' },
    };
    const selected = colors[status] || { bg: '#f3f4f6', color: '#6b7280' }; // safe fallback, no more colors.Fine
    return {
        display: 'inline-block',
        padding: '4px 12px',
        borderRadius: '12px',
        backgroundColor: selected.bg,
        color: selected.color,
        fontSize: '12px',
        fontWeight: '600',
        whiteSpace: 'nowrap',
    };
  },

  statusSelectBorder: (status) => {
    const colors = {
      Fine: '#6366f1',
      Warning: '#a855f7',
      Error: '#ffffff',
      Maintainance: '#94a3b8',
    };
    return { borderColor: colors[status] || colors.Fine, borderWidth: '1.5px' };
  },
  enabledSelectBorder: (status) => ({
    borderColor: status === 'Enabled' ? '#6366f1' : '#9e9e9e',
    borderWidth: '1.5px',
  }),

  customCheckbox: {
    display: 'inline-block',
    position: 'relative',
    cursor: 'pointer',
    fontSize: '22px',
    userSelect: 'none',
    width: '20px',
    height: '20px',
    '& input': {
      position: 'absolute',
      opacity: '0',
      cursor: 'pointer',
      height: '0',
      width: '0',
    },
    '& input:checked ~ span': {
      backgroundColor: '#6366f1',
      borderColor: '#6366f1',
    },
    '& input:checked ~ span:after': {
      display: 'block',
    },
  },
  checkmark: {
    position: 'absolute',
    top: '0',
    left: '0',
    height: '18px',
    width: '18px',
    backgroundColor: 'transparent',
    borderRadius: '3px',
    border: '2px solid #999',
    transition: 'all 0.2s',
    '&:after': {
      content: '""',
      position: 'absolute',
      display: 'none',
      left: '4px',
      top: '0px',
      width: '6px',
      height: '11px',
      border: 'solid white',
      borderWidth: '0 2px 2px 0',
      transform: 'rotate(45deg)',
    },
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(4, 4, 8, 0.65)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    backdropFilter: 'blur(10px)',
  },
  modal: {
    backgroundColor: 'rgba(15, 15, 25, 0.85)',
    borderRadius: '24px',
    padding: '30px',
    maxWidth: '800px',
    width: '90%',
    maxHeight: '90vh',
    overflowY: 'auto',
    border: '1px solid rgba(255, 255, 255, 0.05)',
    boxShadow: '0 28px 70px rgba(0, 0, 0, 0.6)',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
    paddingBottom: '15px',
    borderBottom: '1px solid rgba(255, 255, 255, 0.05)',
  },
  modalTitle: {
    fontSize: '24px',
    fontWeight: '700',
    color: '#ffffff',
    margin: 0,
  },
  modalClose: {
    background: 'none',
    border: 'none',
    fontSize: '24px',
    cursor: 'pointer',
    color: '#a855f7',
    padding: '5px',
  },
  modalBody: {
    marginBottom: '20px',
  },
  modalGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '16px',
  },
  modalField: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  modalLabel: {
    fontSize: '12px',
    fontWeight: '600',
    color: '#94a3b8',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  modalInput: {
    padding: '8px 12px',
    borderRadius: '14px',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    fontSize: '14px',
    outline: 'none',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    color: '#ffffff',
  },
  modalSelect: {
    padding: '8px 12px',
    borderRadius: '14px',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    fontSize: '14px',
    outline: 'none',
    backgroundColor: 'rgba(15, 15, 25, 0.95)',
    color: '#ffffff',
    cursor: 'pointer',
  },
  modalFooter: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    paddingTop: '20px',
    borderTop: '1px solid rgba(255, 255, 255, 0.05)',
  },
  modalCancel: {
    padding: '10px 24px',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    color: '#ffffff',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: '999px',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  modalCreate: {
    padding: '10px 24px',
    background: 'linear-gradient(135deg, #6366f1, #a855f7)',
    color: 'white',
    border: 'none',
    borderRadius: '999px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s',
    boxShadow: '0 4px 12px rgba(99, 102, 241, 0.25)',
  },
  deleteButton: {
    background: 'none',
    border: 'none',
    color: '#ef4444',
    fontSize: '16px',
    cursor: 'pointer',
    padding: '4px 8px',
    borderRadius: '4px',
    transition: 'all 0.2s',
    fontWeight: '600',
  },
  deleteSelectedBtn: {
    background: 'rgba(239, 68, 68, 0.15)',
    color: '#ef4444',
    border: '1px solid rgba(239, 68, 68, 0.3)',
    cursor: 'pointer',
    fontWeight: '600',
    borderRadius: '999px',
    padding: '8px 16px',
    fontSize: '14px',
    marginLeft: '5px',
    flexShrink: 0,
    whiteSpace: 'nowrap',
  },

  paginationBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 0',
    marginTop: '10px',
    borderTop: '1px solid rgba(255,255,255,0.08)',
  },
  paginationInfo: {
    fontSize: '13px',
    color: '#94a3b8',
  },
  paginationControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  pageNavButton: {
    padding: '6px 12px',
    borderRadius: '6px',
    border: '1px solid rgba(255,255,255,0.15)',
    background: 'transparent',
    color: '#e5e7eb',
    cursor: 'pointer',
    fontSize: '13px',
  },
  pageNumber: {
    width: '30px',
    height: '30px',
    borderRadius: '6px',
    border: '1px solid rgba(255,255,255,0.1)',
    background: 'transparent',
    color: '#9aa0aa',
    cursor: 'pointer',
    fontSize: '13px',
  },
  pageNumberActive: {
    width: '30px',
    height: '30px',
    borderRadius: '6px',
    border: '1px solid #6366f1',
    background: '#6366f1',
    color: '#fff',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
  },
  logoutButtonStyle: {
    marginLeft: '10px', 
    cursor: 'pointer',
    color: '#a855f7'
  },
  selectALLButton: {
    display: 'flex',
    alignItems: 'center',
    paddingLeft: '12px',
    marginLeft: '10px',
    cursor: 'pointer'
  }
};
