export const styles = {
    container: {
    minHeight: '100vh',
    width: '100vw', 
    maxWidth: '100%', 
    backgroundColor: '#Fdfaf7', 
    fontFamily: "'Montserrat', sans-serif",
    color: '#1A1A1A',
    display: 'flex',
    flexDirection: 'column',
    boxSizing: 'border-box',
    overflowX: 'hidden', 
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '20px 40px',
    backgroundColor: 'transparent',
    width: '100%',
    boxSizing: 'border-box',
  },
  logoSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
    backgroundColor: '#fff',
    padding: '8px 24px 8px 8px',
    borderRadius: '40px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.03)',
  },
  logoBadge: {
    backgroundColor: '#FF5722',
    color: '#fff',
    width: '36px',
    height: '36px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    fontWeight: 'bold',
  },
  metaText: {
    fontSize: '12px',
    color: '#666',
    fontWeight: '600',
  },
  navSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
  },
  navButton: {
    padding: '10px 24px',
    borderRadius: '30px',
    border: 'none',
    backgroundColor: '#fff',
    color: '#1A1A1A',
    fontWeight: '600',
    cursor: 'pointer',
    boxShadow: '0 4px 12px rgba(0,0,0,0.03)',
  },
  navButtonActive: {
    backgroundColor: '#1A1A1A',
    color: '#fff',
  },
  adminChip: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '6px 20px 6px 6px',
    borderRadius: '30px',
    border: 'none',
    backgroundColor: '#1A1A1A',
    color: '#fff',
    fontWeight: '600',
    cursor: 'pointer',
  },
  adminAvatar: {
    backgroundColor: '#FF5722',
    color: '#fff',
    width: '28px',
    height: '28px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
  },
  mainContent: {
    width: '100%',
    padding: '0 40px 40px 40px',
    display: 'flex',
    flexDirection: 'column',
    gap: '30px',
    boxSizing: 'border-box',
  },
  titleSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
  },
  title: {
    fontSize: '32px',
    fontWeight: '700',
    margin: '0',
  },
  subTitle: {
    fontSize: '14px',
    color: '#666',
    fontWeight: '600',
  },
  actionCardsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', 
    gap: '20px',
    width: '100%',
  },
  actionCard: {
    backgroundColor: '#fff',
    borderRadius: '16px',
    padding: '24px',
    boxShadow: '0 4px 15px rgba(0,0,0,0.02)',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    cursor: 'pointer',
    border: '1px solid transparent',
    transition: 'all 0.2s ease',
  },
  cardIconWrapper: {
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '20px',
    marginBottom: '10px',
    backgroundColor: '#FFF0ED',
  },
  cardTitle: {
    fontSize: '16px',
    fontWeight: '700',
    margin: '0',
  },
  cardDesc: {
    fontSize: '12px',
    color: '#888',
    lineHeight: '1.4',
    margin: '0',
  },
  statsRow: {
    display: 'flex',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    borderRadius: '16px',
    padding: '20px 30px',
    boxShadow: '0 4px 15px rgba(0,0,0,0.02)',
    width: '100%',
    boxSizing: 'border-box',
    flexWrap: 'wrap', 
    gap: '15px',
  },
  statBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    flex: '1 1 min-content', 
  },
  statLabel: {
    fontSize: '12px',
    color: '#888',
    fontWeight: '600',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  statValue: {
    fontSize: '24px',
    fontWeight: '700',
    display: 'flex',
    alignItems: 'baseline',
    gap: '10px',
  },
  statTrendPos: {
    fontSize: '12px',
    color: '#4CAF50',
    fontWeight: '600',
  },
  statTrendNeg: {
    fontSize: '12px',
    color: '#F44336',
    fontWeight: '600',
  },
  tableContainer: {
    backgroundColor: '#fff',
    borderRadius: '16px',
    padding: '20px',
    boxShadow: '0 4px 15px rgba(0,0,0,0.02)',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    width: '100%',
    boxSizing: 'border-box',
  },
  tableControls: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '15px',
  },
  filtersGroup: {
    display: 'flex',
    gap: '10px',
  },
  selectDropdown: {
    padding: '10px 15px',
    borderRadius: '8px',
    border: '1px solid #EAEAEA',
    outline: 'none',
    fontFamily: 'inherit',
    fontSize: '13px',
    color: '#333',
    backgroundColor: '#FAFAFA',
  },
  searchInput: {
    padding: '10px 15px',
    borderRadius: '8px',
    border: '1px solid #EAEAEA',
    outline: 'none',
    fontFamily: 'inherit',
    fontSize: '13px',
    minWidth: '250px',
    backgroundColor: '#FAFAFA',
  },
  primaryActionButton: {
    backgroundColor: '#FFCA28', 
    color: '#1A1A1A',
    border: 'none',
    padding: '10px 20px',
    borderRadius: '8px',
    fontWeight: '700',
    cursor: 'pointer',
  },
  tableHeader: {
    display: 'grid',
    gridTemplateColumns: '0.5fr 1.5fr 2fr 1fr 1fr 1.5fr 1.5fr 1fr 1.5fr 0.5fr',
    padding: '15px 10px',
    borderBottom: '2px solid #F0F0F0',
    fontWeight: '700',
    fontSize: '12px',
    color: '#888',
  },
  tableRow: {
    display: 'grid',
    gridTemplateColumns: '0.5fr 1.5fr 2fr 1fr 1fr 1.5fr 1.5fr 1fr 1.5fr 0.5fr',
    padding: '15px 10px',
    borderBottom: '1px solid #F0F0F0',
    alignItems: 'center',
    fontSize: '13px',
    fontWeight: '600',
  },
  badge: (status) => ({
    padding: '4px 10px',
    borderRadius: '20px',
    fontSize: '11px',
    fontWeight: '700',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    backgroundColor: status === 'Running' ? '#E3F2FD' : 
                     status === 'Completed' ? '#E8F5E9' : 
                     status === 'Failed' ? '#FFEBEE' : '#F5F5F5',
    color: status === 'Running' ? '#1976D2' : 
           status === 'Completed' ? '#388E3C' : 
           status === 'Failed' ? '#D32F2F' : '#757575',
  }),
  progressBarContainer: {
    width: '100%',
    height: '6px',
    backgroundColor: '#E0E0E0',
    borderRadius: '4px',
    marginTop: '4px',
  },
  progressBarFill: (percent) => ({
    width: `${percent}%`,
    height: '100%',
    backgroundColor: percent === 100 ? '#4CAF50' : '#FFCA28',
    borderRadius: '4px',
  }),
  pageLayout: {
    display: 'flex',
    gap: '20px',
    alignItems: 'flex-start',
  },

  actionSidebar: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    width: '260px',
    flexShrink: 0,
    },

    contentColumn: {
        flex: 1,
        minWidth: 0,
    },
};