const colors = {
  white: "#FFFFFF",
  bgSidebar: "#f3f5f0",
  bgActive: "#0c3427",
  border: "#e4e9e1",
  textPrimary: "#697a70",
  textSecondary: "#8e9e94",
  textOnActive: "#ffffff",
  overlay: "rgba(0, 0, 0, 0.3)",
};

export const styles = {
  sidebar: (isCollapsed) => ({
    position: "fixed",
    top: 0,
    left: 0,
    height: "100vh",
    width: isCollapsed ? "80px" : "260px",
    background: colors.bgSidebar,
    borderRight: `1px solid ${colors.border}`,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: isCollapsed ? "24px 10px" : "24px 16px",
    boxSizing: "border-box",
    zIndex: 1000,
    boxShadow: "2px 0 20px rgba(0, 0, 0, 0.03)",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
  }),

  sidebarProfile: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    width: "100%",
    padding: "10px 12px",
    marginBottom: "20px",
    borderRadius: "16px",
    background: "#ffffff",
    border: "1px solid #e4e9e1",
    cursor: "pointer",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.02)",
    transition: "all 0.25s ease",
  },

  sidebarProfileAvatar: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    background: "linear-gradient(135deg, #0c3427 0%, #144837 100%)",
    color: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "800",
    fontSize: "13px",
    boxShadow: "0 4px 10px rgba(12, 52, 39, 0.15)",
  },

  sidebarProfileMeta: {
    display: "flex",
    flexDirection: "column",
    textAlign: "left",
    overflow: "hidden",
  },

  sidebarProfileName: {
    fontSize: "13px",
    fontWeight: "700",
    color: "#12241b",
    lineHeight: "1.3",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
    overflow: "hidden",
  },

  sidebarProfileRole: {
    fontSize: "11px",
    color: "#697a70",
    fontWeight: "500",
  },

  collapseBtn: {
    background: "#ffffff",
    border: "1px solid #e4e9e1",
    borderRadius: "8px",
    width: "28px",
    height: "28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#697a70",
    cursor: "pointer",
    alignSelf: "flex-end",
    marginBottom: "20px",
    padding: 0,
    boxShadow: "0 2px 6px rgba(0, 0, 0, 0.03)",
    transition: "all 0.2s ease",
  },

  floatingOpenBtn: {
    position: "fixed",
    top: "20px",
    left: "20px",
    width: "40px",
    height: "40px",
    borderRadius: "12px",
    background: "#ffffff",
    border: "1px solid #e4e9e1",
    boxShadow: "0 6px 20px rgba(0, 0, 0, 0.08)",
    color: "#0c3427",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    zIndex: 999,
    transition: "all 0.2s cubic-bezier(0.4, 0, 0.2, 1)",
  },

  dismissUpgradeBtn: {
    position: "absolute",
    top: "8px",
    right: "8px",
    background: "rgba(255, 255, 255, 0.15)",
    border: "none",
    borderRadius: "50%",
    width: "18px",
    height: "18px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#ffffff",
    cursor: "pointer",
    fontSize: "10px",
    fontWeight: "700",
    zIndex: 3,
    padding: 0,
  },

  sidebarLogoRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    width: "100%",
    padding: "0 4px",
    marginBottom: "24px",
    justifyContent: "center",
  },

  sidebarLogoBadge: {
    width: "36px",
    height: "36px",
    borderRadius: "12px",
    background: "linear-gradient(135deg, #0c3427, #144837)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: colors.white,
    fontWeight: 800,
    fontSize: "18px",
    boxShadow: "0 4px 12px rgba(12, 52, 39, 0.2)",
  },

  sidebarLogoText: {
    fontSize: "19px",
    fontWeight: 800,
    color: "#0c3427",
    letterSpacing: "-0.02em",
  },

  sectionHeader: {
    fontSize: "10px",
    fontWeight: 700,
    color: "#8e9e94",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    padding: "10px 10px 4px",
    width: "100%",
    textAlign: "left",
  },

  navList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    width: "100%",
  },

  navItemButton: (isActive, isLocked, isCollapsed) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: isCollapsed ? "center" : "flex-start",
    gap: "12px",
    width: "100%",
    padding: "12px 14px",
    borderRadius: "14px",
    border: "none",
    cursor: isLocked ? "not-allowed" : "pointer",
    background: isActive ? colors.bgActive : "transparent",
    opacity: isLocked ? 0.35 : 1,
    color: isActive ? colors.textOnActive : colors.textPrimary,
    fontWeight: isActive ? 700 : 500,
    fontSize: "14px",
    boxShadow: isActive ? "0 4px 14px rgba(12, 52, 39, 0.2)" : "none",
    transition: "all 0.2s ease",
  }),

  navIcon: (isActive, isLocked) => ({
    width: "18px",
    height: "18px",
    objectFit: "contain",
    filter: isActive ? "brightness(0) invert(1)" : "none",
    opacity: isActive ? 1 : 0.65,
  }),

  upgradeCard: {
    background: "linear-gradient(145deg, #0c3427 0%, #062018 100%)",
    borderRadius: "20px",
    padding: "18px 16px",
    color: colors.white,
    marginTop: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    position: "relative",
    overflow: "hidden",
    boxShadow: "0 10px 24px rgba(12, 52, 39, 0.25)",
    width: "100%",
    boxSizing: "border-box",
  },

  upgradeTitle: {
    fontSize: "14px",
    fontWeight: 800,
    margin: 0,
    letterSpacing: "-0.01em",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: "#ffffff",
  },

  upgradeSubtitle: {
    fontSize: "11px",
    color: "#9db3a6",
    lineHeight: "1.4",
    margin: 0,
  },

  upgradeButton: {
    background: colors.white,
    color: "#0c3427",
    border: "none",
    borderRadius: "999px",
    padding: "8px 16px",
    fontWeight: 700,
    fontSize: "12px",
    cursor: "pointer",
    textAlign: "center",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.1)",
    transition: "all 0.2s ease",
  },

  sidebarFooter: {
    marginTop: "12px",
    paddingTop: "12px",
    borderTop: `1px solid ${colors.border}`,
    fontSize: "11px",
    color: colors.textSecondary,
    textAlign: "center",
    width: "100%",
  },
};