const colors = {
  white: "#FFFFFF",
  bgSidebar: "#070708",
  bgActive: "rgba(16, 185, 129, 0.08)",
  border: "#1f1f24",
  textPrimary: "#71717a",
  textSecondary: "#52525b",
  textOnActive: "#10b981",
  overlay: "rgba(0, 0, 0, 0.6)",
};

export const styles = {
  sidebar: (isCollapsed) => ({
    position: "fixed",
    top: 0,
    left: 0,
    height: "100vh",
    width: isCollapsed ? "80px" : "260px",
    background: colors.bgSidebar,
    borderRight: `1px solid ${colors.border}`,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: isCollapsed ? "24px 10px" : "24px 16px",
    boxSizing: "border-box",
    zIndex: 1000,
    boxShadow: "4px 0 30px rgba(0, 0, 0, 0.4)",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
  }),

  sidebarProfile: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    width: "100%",
    padding: "10px 12px",
    marginBottom: "20px",
    borderRadius: "12px",
    background: "#121215",
    border: "1px solid #1f1f24",
    cursor: "pointer",
    transition: "all 0.25s ease",
  },

  sidebarProfileAvatar: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    background: "linear-gradient(135deg, #10b981 0%, #059669 100%)",
    color: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "800",
    fontSize: "13px",
    boxShadow: "0 4px 10px rgba(16, 185, 129, 0.15)",
  },

  sidebarProfileMeta: {
    display: "flex",
    flexDirection: "column",
    textAlign: "left",
    overflow: "hidden",
  },

  sidebarProfileName: {
    fontSize: "13px",
    fontWeight: "700",
    color: "#ffffff",
    lineHeight: "1.3",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
    overflow: "hidden",
  },

  sidebarProfileRole: {
    fontSize: "11px",
    color: "#71717a",
    fontWeight: "500",
  },

  collapseBtn: {
    background: "#121215",
    border: "1px solid #1f1f24",
    borderRadius: "8px",
    width: "28px",
    height: "28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#71717a",
    cursor: "pointer",
    alignSelf: "flex-end",
    marginBottom: "20px",
    padding: 0,
    transition: "all 0.2s ease",
  },

  floatingOpenBtn: {
    position: "fixed",
    top: "20px",
    left: "20px",
    width: "40px",
    height: "40px",
    borderRadius: "10px",
    background: "#070708",
    border: "1px solid #1f1f24",
    boxShadow: "0 8px 24px rgba(0, 0, 0, 0.3)",
    color: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    zIndex: 999,
    transition: "all 0.2s cubic-bezier(0.4, 0, 0.2, 1)",
  },

  dismissUpgradeBtn: {
    position: "absolute",
    top: "8px",
    right: "8px",
    background: "rgba(255, 255, 255, 0.1)",
    border: "none",
    borderRadius: "50%",
    width: "18px",
    height: "18px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#ffffff",
    cursor: "pointer",
    fontSize: "10px",
    fontWeight: "700",
    zIndex: 3,
    padding: 0,
  },

  sidebarLogoRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    width: "100%",
    padding: "0 4px",
    marginBottom: "28px",
    justifyContent: "center",
  },

  sidebarLogoBadge: {
    width: "36px",
    height: "36px",
    borderRadius: "10px",
    background: "linear-gradient(135deg, #10b981, #059669)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: colors.white,
    fontWeight: 800,
    fontSize: "18px",
    boxShadow: "0 8px 20px rgba(16, 185, 129, 0.25)",
  },

  sidebarLogoText: {
    fontSize: "18px",
    fontWeight: 800,
    color: colors.white,
    letterSpacing: "-0.02em",
  },

  sectionHeader: {
    fontSize: "10px",
    fontWeight: 700,
    color: "#3f3f46",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    padding: "12px 10px 6px",
    width: "100%",
    textAlign: "left",
  },

  navList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    width: "100%",
  },

  navItemButton: (isActive, isLocked, isCollapsed) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: isCollapsed ? "center" : "flex-start",
    gap: "12px",
    width: "100%",
    padding: "12px",
    borderRadius: "12px",
    border: isActive ? "1px solid #10b981" : "1px solid transparent",
    cursor: isLocked ? "not-allowed" : "pointer",
    background: isActive ? colors.bgActive : "transparent",
    opacity: isLocked ? 0.35 : 1,
    color: isActive ? colors.textOnActive : colors.textPrimary,
    fontWeight: isActive ? 700 : 600,
    fontSize: "14px",
    transition: "all 0.2s ease",
  }),

  navIcon: (isActive, isLocked) => ({
    width: "18px",
    height: "18px",
    objectFit: "contain",
    filter: isActive ? "none" : "brightness(0) invert(0.5)",
    opacity: 1,
  }),

  upgradeCard: {
    background: "linear-gradient(135deg, #10b981 0%, #059669 100%)",
    borderRadius: "16px",
    padding: "16px",
    color: colors.white,
    marginTop: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    position: "relative",
    overflow: "hidden",
    boxShadow: "0 8px 24px rgba(16, 185, 129, 0.2)",
    width: "100%",
    boxSizing: "border-box",
  },

  upgradeTitle: {
    fontSize: "14px",
    fontWeight: 800,
    margin: 0,
    letterSpacing: "-0.01em",
  },

  upgradeSubtitle: {
    fontSize: "11px",
    opacity: 0.9,
    lineHeight: "1.4",
    margin: 0,
  },

  upgradeButton: {
    background: colors.white,
    color: "#059669",
    border: "none",
    borderRadius: "999px",
    padding: "8px 14px",
    fontWeight: 700,
    fontSize: "11px",
    cursor: "pointer",
    textAlign: "center",
    transition: "all 0.2s ease",
  },

  sidebarFooter: {
    marginTop: "16px",
    paddingTop: "12px",
    borderTop: `1px solid ${colors.border}`,
    fontSize: "11px",
    color: colors.textSecondary,
    textAlign: "center",
    width: "100%",
  },
};