spring.application.name=ibm

spring.datasource.url=jdbc:postgresql://localhost:5432/voltcontrol
spring.datasource.username=postgres
spring.datasource.password=urumbil578
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.encryption.secret-key=PZjRlvdUclLXUuoiu+G2hXKZffJqoAH94l336fV61Hs=